import assert from 'node:assert/strict';
import test from 'node:test';
import { handleRun, createMemoryServices, reconcileRuns, validatePublicBody } from '../v1/runs.js';

const good={contract_version:'1.0',workflow:{slug:'ugc-script-studio'},input:{product_url:'https://example.com/item',brand_voice:'honest',length:30}};
const env={NEON_DATABASE_URL:'postgres://configured',MODAL_UGC_ENDPOINT:'https://modal.test',MODAL_PROXY_TOKEN_ID:'id',MODAL_PROXY_TOKEN_SECRET:'secret',CLERK_PUBLISHABLE_KEY:'pk_test_configured'};
function req(body=good, headers={},method='POST'){return {method,headers,body}}
function res(){return {code:0,body:null,status(n){this.code=n;return this},json(v){this.body=v;return this}}}
const auth={authenticate:async()=>({userId:'user_verified123',method:'clerk'})};
const modalResult={status:'completed',result:{hook:'h',shots:['s'],captions:['c'],cta:'go'}};
const modalResultWithExtra={status:'completed',result:{hook:'h',shots:['s'],captions:['c'],cta:'go',raw:'secret',model:'private'}};
const okFetch=async()=>({ok:true,json:async()=>modalResult});

for (const missing of ['NEON_DATABASE_URL','MODAL_UGC_ENDPOINT','MODAL_PROXY_TOKEN_ID','MODAL_PROXY_TOKEN_SECRET']) test(`fails closed when ${missing} is absent`,async()=>{const e={...env};delete e[missing];const r=res();await handleRun(req(good,{authorization:'Bearer jwt','idempotency-key':'idem_12345678'}),r,e,okFetch,{...auth,store:createMemoryServices().store});assert.equal(r.code,503);assert.equal(r.body.error.code,'SERVER_NOT_CONFIGURED')});

test('never trusts x-user-id and requires verified authentication',async()=>{const r=res();let called=false;await handleRun(req(good,{'x-user-id':'user_attacker','idempotency-key':'idem_12345678'}),r,env,okFetch,{authenticate:async()=>{called=true;return null},store:createMemoryServices().store});assert.equal(called,true);assert.equal(r.code,401);assert.equal(r.body.error.code,'UNAUTHORIZED')});
test('rejects malformed body and unknown canonical fields before dispatch',async()=>{for(const body of [null,{...good,model:'evil'},{...good,workflow:{...good.workflow,endpoint:'evil'}},{...good,input:{...good.input,evil:'x'}}]){const r=res();let calls=0;await handleRun(req(body,{authorization:'Bearer jwt','idempotency-key':'idem_12345678'}),r,env,async()=>{calls++},{...auth,store:createMemoryServices().store});assert.equal(r.code,422);assert.equal(calls,0);assert.equal(r.body.error.retryable,false)}});
test('requires supported methods and a scoped idempotency key',async()=>{for(const [method,key,code] of [['PUT','idem_12345678',405],['POST','short',400]]){const r=res();await handleRun(req(good,{authorization:'Bearer jwt','idempotency-key':key},method),r,env,okFetch,{...auth,store:createMemoryServices().store});assert.equal(r.code,code)}});
test('POST returns 202 after durable claim, dispatches via outbox, settles once, and GET replays canonical result',async()=>{const services=createMemoryServices({balanceCents:100});let calls=0;const deps={...auth,store:services.store};const headers={authorization:'Bearer jwt','idempotency-key':'idem_12345678'};const a=res();await handleRun(req(good,headers),a,env,async()=>{calls++;return {ok:true,json:async()=>modalResult}},deps);assert.equal(a.code,202);assert.equal(a.body.status,'queued');assert.equal(calls,1);assert.equal(services.snapshot().balanceCents,85);assert.deepEqual(services.snapshot().ledger.map(x=>x.kind),['run_debit']);const b=res();await handleRun(req(good,headers),b,env,async()=>{calls++;throw Error('must not dispatch')},deps);assert.equal(b.code,202);assert.deepEqual(b.body,a.body);assert.equal(calls,1);const g=res();await handleRun({method:'GET',headers:{authorization:'Bearer jwt'},query:{run_id:a.body.id}},g,env,okFetch,deps);assert.equal(g.code,200);assert.deepEqual(g.body.result,{hook:'h',shots:['s'],captions:['c'],cta:'go'});assert.equal(g.body.status,'succeeded')});
test('same owner/key with different request is canonical conflict and does not dispatch again',async()=>{const services=createMemoryServices();const headers={authorization:'Bearer jwt','idempotency-key':'idem_12345678'};await handleRun(req(good,headers),res(),env,okFetch,{...auth,store:services.store});let calls=0;const r=res();await handleRun(req({...good,input:{...good.input,length:60}},headers),r,env,async()=>{calls++},{...auth,store:services.store});assert.equal(r.code,409);assert.equal(r.body.error.code,'IDEMPOTENCY_CONFLICT');assert.equal(calls,0)});
test('idempotency scope includes verified owner',async()=>{const services=createMemoryServices();let calls=0;for(const userId of ['user_one123','user_two123']){const r=res();await handleRun(req(good,{authorization:'Bearer jwt','idempotency-key':'idem_12345678','x-user-id':'same-spoof'}),r,env,async()=>{calls++;return {ok:true,json:async()=>modalResult}},{authenticate:async()=>({userId}),store:services.store});assert.equal(r.code,202)}assert.equal(calls,2)});
test('GET is owner-scoped and includes canonical contract errors',async()=>{const services=createMemoryServices();const create=res();await handleRun(req(good,{authorization:'Bearer jwt','idempotency-key':'idem_12345678'}),create,env,okFetch,{...auth,store:services.store});const denied=res();await handleRun({method:'GET',headers:{authorization:'Bearer jwt'},query:{run_id:create.body.id}},denied,env,okFetch,{authenticate:async()=>({userId:'user_other123'}),store:services.store});assert.equal(denied.code,404);assert.equal(denied.body.error.contract_version,'1.0')});
test('invalid Modal output including extra fields refunds exactly once and persists failed canonical run',async()=>{for(const data of [modalResultWithExtra,{status:'completed',result:{hook:'h',shots:['s'],captions:['c']}},{status:'completed',result:{hook:'h',shots:['s'],captions:[2],cta:'x'}},{status:'weird',result:{}}]){const services=createMemoryServices({balanceCents:100});const headers={authorization:'Bearer jwt','idempotency-key':'idem_'+Math.random().toString(36).slice(2,14)};const r=res();await handleRun(req(good,headers),r,env,async()=>({ok:true,json:async()=>data}),{...auth,store:services.store});assert.equal(r.code,202);assert.equal(r.body.status,'queued');const get=res();await handleRun({method:'GET',headers:{authorization:'Bearer jwt'},query:{run_id:r.body.id}},get,env,okFetch,{...auth,store:services.store});assert.equal(get.code,502);assert.equal(get.body.status,'failed');assert.equal(get.body.error.code,'INVALID_PROVIDER_OUTPUT');assert.equal(services.snapshot().balanceCents,100);assert.deepEqual(services.snapshot().ledger.map(x=>x.kind),['run_debit','run_refund'])}});
test('network and 5xx failures remain queued without refund while malformed JSON is terminal',async()=>{for(const fetcher of [async()=>{throw Error('secret')},async()=>({ok:false,status:500,json:async()=>({raw:'secret'})})]){const services=createMemoryServices({balanceCents:100});const r=res();await handleRun(req(good,{authorization:'Bearer jwt','idempotency-key':'idem_'+Math.random().toString(36).slice(2,14)}),r,env,fetcher,{...auth,store:services.store});const get=res();await handleRun({method:'GET',headers:{authorization:'Bearer jwt'},query:{run_id:r.body.id}},get,env,okFetch,{...auth,store:services.store});assert.equal(get.code,202);assert.equal(get.body.status,'queued');assert.equal(services.snapshot().balanceCents,85);assert.equal(JSON.stringify(get.body).includes('secret'),false)}const services=createMemoryServices({balanceCents:100});const r=res();await handleRun(req(good,{authorization:'Bearer jwt','idempotency-key':'malformed_123456'}),r,env,async()=>({ok:true,json:async()=>{throw Error('secret')}}),{...auth,store:services.store});const get=res();await handleRun({method:'GET',headers:{authorization:'Bearer jwt'},query:{run_id:r.body.id}},get,env,okFetch,{...auth,store:services.store});assert.equal(get.code,502);assert.equal(get.body.error.code,'INVALID_PROVIDER_OUTPUT');assert.equal(services.snapshot().balanceCents,100)});
test('insufficient balance never dispatches and persists payment failure without refund credit',async()=>{const services=createMemoryServices({balanceCents:1});let calls=0;const r=res();await handleRun(req(good,{authorization:'Bearer jwt','idempotency-key':'idem_12345678'}),r,env,async()=>{calls++},{...auth,store:services.store});assert.equal(r.code,402);assert.equal(r.body.status,'failed');assert.equal(r.body.error.code,'PAYMENT_REQUIRED');assert.equal(calls,0);assert.deepEqual(services.snapshot().ledger,[])});
test('stale lease recovery redispatches with run id idempotency and does not double debit',async()=>{const services=createMemoryServices({balanceCents:100});const timestamp='2026-08-12T00:00:00.000Z';const row={run_id:'run_stalelease123',user_id:'user_verified123',request_hash:'hash',slug:'ugc-script-studio',workflow_version:'1.0.0',cost_cents:15,execution_status:'claimed',billing_status:'unbilled',input:good.input,created_at:timestamp,updated_at:timestamp,attempt_count:0,artifacts:[]};await services.store.claim(row.user_id,'idem_stale_lease','hash',row);assert.equal(await services.store.reserve(row.user_id,15,row.run_id),true);await services.store.markQueued(row);await services.store.lease(row.run_id,'crashed-owner','2000-01-01T00:00:00.000Z');let calls=0;await reconcileRuns(services.store,env,async(url,options)=>{calls++;assert.equal(options.headers['x-cognition-run-id'],row.run_id);return {ok:true,json:async()=>modalResult}},{limit:5});const g=res();await handleRun({method:'GET',headers:{authorization:'Bearer jwt'},query:{run_id:row.run_id}},g,env,okFetch,{...auth,store:services.store});assert.equal(g.body.status,'succeeded');assert.equal(calls,1);assert.equal(services.snapshot().balanceCents,85);assert.deepEqual(services.snapshot().ledger.map(x=>x.kind),['run_debit'])});

test('canonical artifact refs are enforced at runtime',()=>{const run={contract_version:'1.0',id:'run_artifact123',workflow:{slug:'ugc-script-studio',version:'1.0.0'},status:'queued',created_at:'2026-08-12T00:00:00.000Z',updated_at:'2026-08-12T00:00:00.000Z',result:null,artifacts:[{id:'only-id'}],error:null};assert.throws(()=>validatePublicBody(run),/invalid public response/);run.artifacts=[{id:'a1',kind:'document',media_type:'text/plain',filename:'result.txt',url:'https://example.com/result.txt',expires_at:null,size_bytes:12,checksum_sha256:'a'.repeat(64)}];assert.deepEqual(validatePublicBody(run),run)});

test('reconciler recovers a crash immediately after durable claim',async()=>{const services=createMemoryServices({balanceCents:100});const timestamp='2026-08-12T00:00:00.000Z';const row={run_id:'run_claimedrecovery123',user_id:'user_verified123',request_hash:'hash',slug:'ugc-script-studio',workflow_version:'1.0.0',cost_cents:15,execution_status:'claimed',billing_status:'unbilled',input:good.input,created_at:timestamp,updated_at:timestamp,attempt_count:0,artifacts:[]};await services.store.claim(row.user_id,'idem_claimed_recovery','hash',row);let calls=0;await reconcileRuns(services.store,env,async()=>{calls++;return {ok:true,json:async()=>modalResult}},{limit:5});assert.equal(calls,1);assert.equal(row.execution_status,'succeeded');assert.equal(row.billing_status,'captured');assert.equal(services.snapshot().balanceCents,85);assert.deepEqual(services.snapshot().ledger.map(x=>x.kind),['run_debit'])});

const facebookInput={product_name:'Northstar Skillet',offer:'A cast-iron skillet with free shipping',audience:'Busy home cooks seeking easier dinners',objective:'sales',tone:'direct',proof_points:'Pre-seasoned and oven-safe',constraints:''};
const facebookRequest={contract_version:'1.0',workflow:{slug:'facebook-ads-copywriter',version:'0.1.0'},input:facebookInput};
const facebookEnv={...env,MODAL_FACEBOOK_ADS_ENDPOINT:'https://modal.test/v1/runs'};
const ad={angle:'Weeknight ease',primary_text:'A'.repeat(50),headline:'Dinner made simpler',description:'Reliable cast-iron cooking',cta:'Shop Now'};
const facebookOutput={run_id:'modal_call_123',status:'completed',workflow_version:'facebook-ads-copywriter@0.1.0',campaign_summary:'Three verified campaign directions.',ads:[ad,{...ad,angle:'Lasting quality'},{...ad,angle:'Free shipping'}],testing_notes:['Test headline first.','Compare direct and benefit-led angles.'],compliance_notes:['Uses only supplied product facts.'],usage:{provider:'opencode-go',model:'deepseek',llm_calls:1,prompt_tokens:10,completion_tokens:20,estimated_cost_usd:0.003}};

test('Facebook canonical request costs ten cents and async acceptance stays running until reconciliation polls result_url',async()=>{const services=createMemoryServices({balanceCents:100});const calls=[];const fetcher=async(url,options={})=>{calls.push([url,options.method||'GET']);if((options.method||'GET')==='POST')return {ok:true,json:async()=>({call_id:'modal_call_123',result_url:'/v1/runs/modal_call_123',status:'accepted'})};return {ok:true,json:async()=>calls.length===2?{call_id:'modal_call_123',status:'running'}:facebookOutput}};const created=res();await handleRun(req(facebookRequest,{authorization:'Bearer jwt','idempotency-key':'facebook_12345678'}),created,facebookEnv,fetcher,{...auth,store:services.store});assert.equal(created.code,202);assert.equal(created.body.status,'queued');assert.equal(services.snapshot().balanceCents,90);let got=res();await handleRun({method:'GET',headers:{authorization:'Bearer jwt'},query:{run_id:created.body.id}},got,facebookEnv,fetcher,{...auth,store:services.store});assert.equal(got.body.status,'running');await reconcileRuns(services.store,facebookEnv,fetcher);got=res();await handleRun({method:'GET',headers:{authorization:'Bearer jwt'},query:{run_id:created.body.id}},got,facebookEnv,fetcher,{...auth,store:services.store});assert.equal(got.body.status,'running');await reconcileRuns(services.store,facebookEnv,fetcher);got=res();await handleRun({method:'GET',headers:{authorization:'Bearer jwt'},query:{run_id:created.body.id}},got,facebookEnv,fetcher,{...auth,store:services.store});assert.equal(got.body.status,'succeeded');assert.deepEqual(got.body.result,facebookOutput);assert.deepEqual(calls.map(x=>x[1]),['POST','GET','GET']);assert.deepEqual(services.snapshot().ledger.map(x=>x.kind),['run_debit'])});

test('Facebook terminal Modal failure polls manifest path and refunds once across repeated reconciliation',async()=>{const services=createMemoryServices({balanceCents:100});const calls=[];const fetcher=async(url,options={})=>{calls.push([url,options.method||'GET']);return options.method==='POST'?{ok:true,json:async()=>({call_id:'modal_fail_1',result_url:'https://modal.test/v1/runs/modal_fail_1',status:'accepted'})}:{ok:true,json:async()=>({call_id:'modal_fail_1',status:'failed',error:{message:'provider detail'}})}};const created=res();await handleRun(req(facebookRequest,{authorization:'Bearer jwt','idempotency-key':'facebook_fail_123'}),created,facebookEnv,fetcher,{...auth,store:services.store});await reconcileRuns(services.store,facebookEnv,fetcher);await reconcileRuns(services.store,facebookEnv,fetcher);const row=[...services.snapshot().runs.values()][0];assert.deepEqual(calls,[['https://modal.test/v1/runs','POST'],['https://modal.test/v1/runs/modal_fail_1','GET']]);assert.equal(row.error.code,'PROVIDER_FAILED');assert.equal(services.snapshot().balanceCents,100);assert.deepEqual(services.snapshot().ledger.map(x=>x.kind),['run_debit','run_refund'])});
