"""Generated Modal contract runtime for grapheme-to-phoneme-converter.

Generated by skill-to-modal/0.2.1; change the profile/compiler, not this file.
Complex or unapproved capabilities fail closed. Tests inject a pure mock
executor and never make provider calls.
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
import uuid
from functools import lru_cache
from pathlib import Path
from typing import Any, Callable

import modal
from jsonschema import Draft202012Validator


APP_NAME = 'cognition-grapheme-to-phoneme-converter'
WORKFLOW_VERSION = 'grapheme-to-phoneme-converter@0.1.0'
EXECUTION_KIND = 'single_llm'
LOCAL_ROOT = Path(__file__).resolve().parent
IMAGE_ROOT = Path('/root/grapheme_to_phoneme_converter')

LIVE_PROVIDER = 'opencode-go'
LIVE_BASE_URL_ENV = 'LLM_BASE_URL'
LIVE_MODEL_ENV = 'LLM_MODEL'
LIVE_API_KEY_ENV = 'LLM_API_KEY'
LIVE_DEFAULT_BASE_URL = 'https://opencode.ai/zen/go/v1'
LIVE_DEFAULT_MODEL = 'deepseek-v4-flash'
LIVE_PROMPT_PATH = 'prompts/run.txt'
LIVE_MAX_TOKENS = 1200
LIVE_TEMPERATURE = 0.2
LIVE_TIMEOUT_SECONDS = 120
LIVE_INPUT_RATE_PER_MILLION = 0.14
LIVE_OUTPUT_RATE_PER_MILLION = 0.42
LIVE_MODEL_OUTPUT_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema', 'type': 'object', 'additionalProperties': False, 'properties': {'input': {'type': 'string', 'minLength': 1, 'maxLength': 80}, 'dialect': {'enum': ['en-US', 'en-GB', 'en-AU']}, 'phonemes': {'type': 'array', 'items': {'type': 'string', 'minLength': 1, 'maxLength': 20}, 'minItems': 1, 'maxItems': 30}, 'ipa': {'type': 'string', 'maxLength': 120}, 'rules_explanation': {'type': 'string', 'maxLength': 800}, 'example_words': {'type': 'array', 'items': {'type': 'string', 'minLength': 1, 'maxLength': 80}, 'maxItems': 5}, 'uncertainty': {'type': 'string', 'minLength': 1, 'maxLength': 300}}, 'required': ['input', 'dialect', 'phonemes', 'ipa', 'rules_explanation', 'example_words', 'uncertainty']}



class WorkflowNotReady(RuntimeError):
    """Raised before spend when the reviewed workflow cannot run live."""


class ProviderCallError(RuntimeError):
    """Safe provider failure code; response bodies and credentials are never logged."""


def _asset_root() -> Path:
    return LOCAL_ROOT if (LOCAL_ROOT / "schemas" / "input.json").is_file() else IMAGE_ROOT


@lru_cache(maxsize=None)
def load_json(relative_path: str) -> dict[str, Any]:
    with (_asset_root() / relative_path).open(encoding="utf-8") as handle:
        return json.load(handle)


@lru_cache(maxsize=None)
def load_schema(name: str) -> dict[str, Any]:
    schema = load_json(f"schemas/{name}")
    Draft202012Validator.check_schema(schema)
    return schema


def validate_instance(instance: Any, schema_name: str) -> None:
    Draft202012Validator(load_schema(schema_name)).validate(instance)


def readiness() -> dict[str, Any]:
    return load_json("manifest.json")["readiness"]


def _extract_json_object(value: str) -> dict[str, Any]:
    fenced = re.sub(r"^```(?:json)?\s*|\s*```$", "", value.strip(), flags=re.I)
    parsed = json.loads(fenced)
    if not isinstance(parsed, dict):
        raise ValueError("provider output must be a JSON object")
    return parsed


_ALIAS_GROUPS = (
    {"count", "number", "total"},
    {"input", "text", "source"},
    {"text", "digraph", "grapheme", "pattern"},
    {"word", "token"},
    {"syllabified", "syllables", "split"},
    {"ambiguity", "ambiguity_note", "note", "notes"},
    {"possible_confusions", "confusion_labels", "confusions", "labels"},
    {"practice_suggestions", "practice_ideas", "practice"},
    {"observation", "hypothesis"},
    {"premise", "story", "story_idea", "logline"},
    {"writing_hook", "hook"},
    {"rules_explanation", "rules", "explanation"},
    {"example_words", "examples"},
    {"target_words", "words"},
    {"sight_or_irregular_words", "sight_words", "irregular_words"},
    {"matched_phonemes", "phonemes"},
    {"target_position", "position"},
    {"pronunciation_note", "note", "notes"},
    {"rule", "phonics_rule", "phonics_pattern", "pattern"},
    {"constraints_used", "constraints"},
)


def _key_tokens(value: str) -> set[str]:
    words = re.findall(r"[a-z0-9]+", re.sub(r"([a-z])([A-Z])", r"\1_\2", value).lower())
    return {word[:-1] if word.endswith("s") and len(word) > 3 else word for word in words}


def _schema_types(schema: dict[str, Any]) -> set[str]:
    declared = schema.get("type")
    if isinstance(declared, str):
        return {declared}
    if isinstance(declared, list):
        return {str(item) for item in declared}
    if "const" in schema:
        value = schema["const"]
        if isinstance(value, bool):
            return {"boolean"}
        if isinstance(value, int):
            return {"integer"}
        if isinstance(value, str):
            return {"string"}
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return _schema_types({"const": schema["enum"][0]})
    return set()


def _value_type(value: Any) -> str:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    return "null"


def _alias_score(source: str, target: str, value: Any, schema: dict[str, Any]) -> int:
    if source == target:
        return 1000
    source_tokens = _key_tokens(source)
    target_tokens = _key_tokens(target)
    score = 0
    if source_tokens and target_tokens:
        overlap = source_tokens & target_tokens
        if overlap:
            score = max(score, 72 + 4 * len(overlap))
        if source_tokens <= target_tokens or target_tokens <= source_tokens:
            score = max(score, 82)
    for group in _ALIAS_GROUPS:
        group_tokens = set().union(*(_key_tokens(item) for item in group))
        if source_tokens & group_tokens and target_tokens & group_tokens:
            score = max(score, 68)
    expected = _schema_types(schema)
    actual = _value_type(value)
    if actual in expected or (actual == "integer" and "number" in expected):
        score += 8
    elif expected:
        coercible = actual == "string" and (
            "array" in expected
            or ("integer" in expected and bool(re.fullmatch(r"[-+]?\d+", value.strip())))
            or ("number" in expected and bool(re.fullmatch(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)", value.strip())))
            or ("boolean" in expected and value.strip().lower() in {"true", "false", "yes", "no", "1", "0"})
        )
        if not coercible:
            score -= 30
    return score


def _default_required(
    name: str,
    schema: dict[str, Any],
    context: dict[str, Any],
    repaired: dict[str, Any],
) -> tuple[bool, Any]:
    if "const" in schema:
        return True, schema["const"]
    if name == "type":
        requested = context.get("digraph_type")
        if requested in {"consonant", "vowel"}:
            return True, requested
        text = str(repaired.get("text") or "").lower()
        vowel_digraphs = {"ai", "au", "aw", "ay", "ea", "ee", "ew", "ie", "oa", "oe", "oi", "oo", "ou", "ow", "oy", "ue", "ui"}
        if text:
            return True, "vowel" if text in vowel_digraphs else "consonant"
    candidates = sorted(
        (
            (_alias_score(source, name, value, schema), source, value)
            for source, value in context.items()
        ),
        reverse=True,
    )
    if candidates and candidates[0][0] >= 68:
        return True, candidates[0][2]
    if name.endswith("_count"):
        prefix = _key_tokens(name.removesuffix("_count"))
        for sibling, value in repaired.items():
            if isinstance(value, list) and prefix & _key_tokens(sibling):
                return True, len(value)
    if name == "word" and isinstance(context.get("text"), str):
        start, end = repaired.get("start"), repaired.get("end")
        if isinstance(start, int) and isinstance(end, int):
            source_text = context["text"]
            left, right = start, end
            while left > 0 and (source_text[left - 1].isalnum() or source_text[left - 1] in "'-"):
                left -= 1
            while right < len(source_text) and (source_text[right].isalnum() or source_text[right] in "'-"):
                right += 1
            if left < right:
                return True, source_text[left:right]
    if name == "target_position":
        word = str(repaired.get("word") or "").lower()
        matches = repaired.get("matched_phonemes")
        if word and isinstance(matches, list):
            positions: set[str] = set()
            for match in matches:
                needle = str(match).lower()
                index = word.find(needle)
                if index < 0:
                    continue
                if word.find(needle, index + 1) >= 0:
                    positions.add("multiple")
                elif index == 0:
                    positions.add("initial")
                elif index + len(needle) == len(word):
                    positions.add("final")
                else:
                    positions.add("medial")
            if positions:
                return True, sorted(positions)[0] if len(positions) == 1 else "multiple"
    if name == "target_words":
        source = context.get("__generated__")
        coverage = source.get("coverage") if isinstance(source, dict) else None
        sentence = str(repaired.get("text") or "").lower()
        if isinstance(coverage, dict) and sentence:
            words: list[str] = []
            for covered in coverage.values():
                if not isinstance(covered, list):
                    continue
                for word in covered:
                    text = str(word)
                    if re.search(r"(?<![A-Za-z])" + re.escape(text.lower()) + r"(?![A-Za-z])", sentence):
                        words.append(text)
            if words:
                return True, words
    if name == "explanation" and isinstance(repaired.get("observation"), str):
        return True, repaired["observation"]
    if name == "uncertainty":
        dialect = str(context.get("dialect") or "the selected dialect")
        return True, f"Pronunciation may vary by speaker in {dialect}; review before teaching."
    if name in {"note", "pronunciation_note"}:
        dialect = str(context.get("dialect") or "the selected dialect")
        return True, f"Review this example in {dialect}."
    if name == "ambiguity_note":
        return True, ""
    if name == "writing_hook" and isinstance(repaired.get("premise"), str):
        premise = repaired["premise"].strip()
        if premise:
            return True, ("What happens next? " + premise)[:240]
    expected = _schema_types(schema)
    if "array" in expected and int(schema.get("minItems", 0)) == 0:
        return True, []
    if "string" in expected and int(schema.get("minLength", 0)) == 0:
        return True, ""
    if "object" in expected and not schema.get("required"):
        return True, {}
    return False, None


def _coerce_to_schema(value: Any, schema: dict[str, Any], context: dict[str, Any]) -> Any:
    expected = _schema_types(schema)
    if "object" in expected:
        properties = schema.get("properties") if isinstance(schema.get("properties"), dict) else {}
        if not isinstance(value, dict):
            seed: dict[str, Any] = {}
            for preferred in ("text", "word", "answer", "title", "premise", "value"):
                if preferred in properties:
                    seed[preferred] = value
                    break
            value = seed
        repaired: dict[str, Any] = {}
        used_sources: set[str] = set()
        for name, child_schema in properties.items():
            if name in value:
                repaired[name] = _coerce_to_schema(value[name], child_schema, context)
                used_sources.add(name)
        for source, child_value in value.items():
            if source in used_sources:
                continue
            choices = sorted(
                (
                    (_alias_score(source, target, child_value, child_schema), target, child_schema)
                    for target, child_schema in properties.items()
                    if target not in repaired
                ),
                reverse=True,
            )
            if choices and choices[0][0] >= 68:
                _, target, child_schema = choices[0]
                repaired[target] = _coerce_to_schema(child_value, child_schema, context)
        for name in schema.get("required", []):
            if name in repaired or name not in properties:
                continue
            found, default = _default_required(name, properties[name], context, repaired)
            if found:
                repaired[name] = _coerce_to_schema(default, properties[name], context)
        for name, child_schema in properties.items():
            allowed = child_schema.get("enum") if isinstance(child_schema, dict) else None
            if name in repaired and isinstance(allowed, list) and repaired[name] not in allowed:
                found, default = _default_required(name, child_schema, context, repaired)
                if found:
                    repaired[name] = _coerce_to_schema(default, child_schema, context)
        return repaired
    if "array" in expected:
        item_schema = schema.get("items") if isinstance(schema.get("items"), dict) else {}
        if isinstance(value, dict) and "object" not in _schema_types(item_schema):
            value = list(value)
        elif not isinstance(value, list):
            if isinstance(value, str) and re.search(r"[,;\n]", value):
                value = [part.strip() for part in re.split(r"[,;\n]+", value) if part.strip()]
            else:
                value = [value]
        repaired_items = [_coerce_to_schema(item, item_schema, context) for item in value]
        if schema.get("uniqueItems"):
            unique: list[Any] = []
            seen: set[str] = set()
            for item in repaired_items:
                marker = json.dumps(item, ensure_ascii=False, sort_keys=True)
                if marker not in seen:
                    seen.add(marker)
                    unique.append(item)
            repaired_items = unique
        maximum = schema.get("maxItems")
        return repaired_items[: int(maximum)] if isinstance(maximum, int) else repaired_items
    if "integer" in expected:
        if isinstance(value, str) and re.fullmatch(r"[-+]?\d+", value.strip()):
            return int(value.strip())
        if isinstance(value, float) and value.is_integer():
            return int(value)
        return value
    if "number" in expected:
        if isinstance(value, str):
            try:
                return float(value.strip())
            except ValueError:
                return value
        return value
    if "boolean" in expected and isinstance(value, str):
        if value.strip().lower() in {"true", "yes", "1"}:
            return True
        if value.strip().lower() in {"false", "no", "0"}:
            return False
    if "string" in expected:
        if value is None and int(schema.get("minLength", 0)) == 0:
            value = ""
        elif isinstance(value, list) and all(not isinstance(item, (dict, list)) for item in value):
            value = ", ".join(str(item) for item in value)
        elif not isinstance(value, str) and value is not None:
            value = str(value)
        maximum = schema.get("maxLength")
        if isinstance(value, str) and isinstance(maximum, int):
            value = value[:maximum]
        minimum = schema.get("minLength")
        if isinstance(value, str) and isinstance(minimum, int) and len(value) < minimum:
            suffix = " Review the supplied context and dialect before teaching."
            value = (value + suffix)[: int(schema.get("maxLength", len(value) + len(suffix)))]
    return value


def _repair_to_schema(
    generated: dict[str, Any], schema: dict[str, Any], prompt_input: dict[str, Any]
) -> dict[str, Any]:
    context = dict(prompt_input)
    context["__generated__"] = generated
    repaired = _coerce_to_schema(generated, schema, context)
    return repaired if isinstance(repaired, dict) else {}


def _validation_diff(instance: Any, schema: dict[str, Any]) -> str:
    errors = sorted(
        Draft202012Validator(schema).iter_errors(instance),
        key=lambda error: (list(error.absolute_path), str(error.validator)),
    )
    details: list[str] = []
    for error in errors[:20]:
        path = "$" + "".join(
            f"[{part}]" if isinstance(part, int) else f".{part}" for part in error.absolute_path
        )
        if error.validator == "required" and isinstance(error.instance, dict):
            missing = [name for name in error.validator_value if name not in error.instance]
            detail = "required(" + ",".join(missing) + ")"
        elif error.validator == "additionalProperties" and isinstance(error.instance, dict):
            allowed = set(error.schema.get("properties", {}))
            extra_count = sum(1 for name in error.instance if name not in allowed)
            detail = f"additionalProperties(count={extra_count})"
        elif error.validator == "type":
            detail = "type(expected=" + str(error.validator_value) + ")"
        elif error.validator in {"minLength", "maxLength", "minItems", "maxItems", "minimum", "maximum", "enum", "const", "uniqueItems"}:
            detail = str(error.validator) + "(expected=" + str(error.validator_value)[:160] + ")"
        else:
            detail = str(error.validator)
        details.append(path + ":" + detail)
    if len(errors) > 20:
        details.append(f"...+{len(errors) - 20}_more")
    return ";".join(details)


def _provider_request(
    base_url: str,
    model: str,
    messages: list[dict[str, str]],
) -> tuple[str, dict[str, Any]]:
    request_body = {
        "model": model,
        "messages": messages,
        "temperature": LIVE_TEMPERATURE,
        "max_tokens": LIVE_MAX_TOKENS,
        "response_format": {"type": "json_object"},
        "thinking": {"type": "disabled"},
    }
    request = urllib.request.Request(
        base_url + "/chat/completions",
        data=json.dumps(request_body).encode("utf-8"),
        headers={
            "Authorization": "Bearer " + os.environ[LIVE_API_KEY_ENV],
            "Content-Type": "application/json",
            "User-Agent": "Omo-Skill-Runner/0.2",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=LIVE_TIMEOUT_SECONDS) as response:
            raw = response.read(2_000_001)
    except urllib.error.HTTPError as exc:
        raise ProviderCallError(f"LLM_HTTP_{exc.code}") from exc
    except (urllib.error.URLError, TimeoutError) as exc:
        raise ProviderCallError("LLM_UNAVAILABLE") from exc
    if len(raw) > 2_000_000:
        raise ProviderCallError("LLM_RESPONSE_TOO_LARGE")
    try:
        provider_response = json.loads(raw)
        content = str(provider_response["choices"][0]["message"]["content"])
    except Exception as exc:
        raise ProviderCallError("LLM_RESPONSE_INVALID") from exc
    return content, provider_response


def _candidate(
    content: str, payload: dict[str, Any]
) -> tuple[dict[str, Any] | None, str]:
    try:
        parsed = _extract_json_object(content)
    except Exception:
        return None, "$:invalid_json"
    repaired = _repair_to_schema(parsed, LIVE_MODEL_OUTPUT_SCHEMA, payload)
    return repaired, _validation_diff(repaired, LIVE_MODEL_OUTPUT_SCHEMA)


def _provider_completion(payload: dict[str, Any]) -> dict[str, Any]:
    missing = [name for name in readiness()["required_env_names"] if not os.environ.get(name)]
    if missing:
        raise WorkflowNotReady("MISSING_REQUIRED_ENV:" + ",".join(sorted(missing)))

    base_url = os.environ[LIVE_BASE_URL_ENV].rstrip("/")
    if not base_url.startswith("https://"):
        raise WorkflowNotReady("LLM_BASE_URL_MUST_BE_HTTPS")
    model = os.environ[LIVE_MODEL_ENV]
    system_prompt = (_asset_root() / LIVE_PROMPT_PATH).read_text(encoding="utf-8").strip()
    schema_contract = json.dumps(
        LIVE_MODEL_OUTPUT_SCHEMA, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    )
    system_prompt += (
        "\n\nOUTPUT CONTRACT (mandatory): Return exactly one JSON object matching this "
        "JSON Schema. Use exactly the declared field names and types, include every "
        "required field, and include no undeclared fields:\n" + schema_contract
    )
    user_prompt = "Run the reviewed workflow using only this JSON input:\n" + json.dumps(
        payload, ensure_ascii=False, sort_keys=True
    )
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    content, first_response = _provider_request(base_url, model, messages)
    generated, validation_diff = _candidate(content, payload)
    responses = [first_response]
    if validation_diff:
        corrective = (
            "CORRECTIVE RETRY (final attempt): the previous JSON failed validation. "
            "Fix exactly these schema violations: " + validation_diff + ". "
            "Return the complete corrected JSON object only; use the exact schema in "
            "the system instruction and invent no fields. Do not repeat or quote "
            "input values, credentials, prior response text, or undeclared field names."
        )
        try:
            retry_content, retry_response = _provider_request(
                base_url,
                model,
                messages + [{"role": "user", "content": corrective}],
            )
        except ProviderCallError as exc:
            raise ProviderCallError(
                "LLM_INVALID_OUTPUT:" + validation_diff + ";retry=" + str(exc)
            ) from exc
        responses.append(retry_response)
        generated, retry_diff = _candidate(retry_content, payload)
        if retry_diff or generated is None:
            raise ProviderCallError("LLM_INVALID_OUTPUT:" + (retry_diff or "$:invalid_json"))
    if generated is None:
        raise ProviderCallError("LLM_INVALID_OUTPUT:" + (validation_diff or "$:unknown"))

    prompt_tokens = sum(max(0, int((response.get("usage") or {}).get("prompt_tokens") or 0)) for response in responses)
    completion_tokens = sum(max(0, int((response.get("usage") or {}).get("completion_tokens") or 0)) for response in responses)
    estimated_cost = (
        prompt_tokens * LIVE_INPUT_RATE_PER_MILLION
        + completion_tokens * LIVE_OUTPUT_RATE_PER_MILLION
    ) / 1_000_000
    return {
        "run_id": "run-" + str(uuid.uuid4()),
        "status": "completed",
        "workflow_version": WORKFLOW_VERSION,
        **generated,
        "usage": {
            "provider": LIVE_PROVIDER,
            "model": str(responses[-1].get("model") or model),
            "llm_calls": len(responses),
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "estimated_cost_usd": round(estimated_cost, 8),
        },
    }



Executor = Callable[[dict[str, Any]], dict[str, Any]]


def execute_workflow(
    payload: dict[str, Any], *, executor: Executor | None = None
) -> dict[str, Any]:
    """Validate, execute once, and validate output.

    A mock executor is an explicit offline test seam. The generated live
    candidate never substitutes mock artifacts for unavailable providers.
    """
    validate_instance(payload, "input.json")
    if executor is None:
        state = readiness()
        if not state["can_submit"]:
            raise WorkflowNotReady(
                "; ".join(reason["code"] for reason in state["blockers"])
            )
        executor = _provider_completion
    result = executor(payload)
    validate_instance(result, "output.json")
    return result


runtime_image = (
    modal.Image.debian_slim(python_version="3.12")
    .uv_pip_install(
        "modal==1.5.0",
        "fastapi==0.109.0",
        "jsonschema==4.26.0",
    )
    .add_local_dir(LOCAL_ROOT / "schemas", IMAGE_ROOT / "schemas", copy=True)
    .add_local_dir(LOCAL_ROOT / "prompts", IMAGE_ROOT / "prompts", copy=True)
    .add_local_file(LOCAL_ROOT / "manifest.json", str(IMAGE_ROOT / "manifest.json"), copy=True)
)

app = modal.App(APP_NAME)


@app.function(
    image=runtime_image,
    cpu=1,
    memory=512,
    timeout=270,
    min_containers=0,
    max_containers=4,
    scaledown_window=5,
    secrets=[modal.Secret.from_name('omo-skill-providers')],
)
def run_workflow(payload: dict[str, Any]) -> dict[str, Any]:
    return execute_workflow(payload)


SpawnRunner = Callable[[dict[str, Any]], str]
LookupResult = Callable[[str], dict[str, Any]]


def create_fastapi_app(
    spawn_runner: SpawnRunner | None = None,
    lookup_result: LookupResult | None = None,
    *,
    ready_override: bool | None = None,
) -> Any:
    from fastapi import Body, FastAPI, HTTPException
    from fastapi.responses import JSONResponse
    from jsonschema import ValidationError

    web = FastAPI(title='grapheme-to-phoneme-converter', version='0.1.0')

    def default_spawn(payload: dict[str, Any]) -> str:
        return run_workflow.spawn(payload).object_id

    def default_lookup(call_id: str) -> dict[str, Any]:
        return modal.FunctionCall.from_id(call_id).get(timeout=0)

    spawn = spawn_runner or default_spawn
    lookup = lookup_result or default_lookup

    @web.post("/v1/runs", status_code=202)
    async def submit(body: Any = Body(...)) -> Any:
        try:
            validate_instance(body, "input.json")
        except ValidationError as exc:
            raise HTTPException(status_code=422, detail=exc.message) from exc

        state = readiness()
        can_submit = state["can_submit"] if ready_override is None else ready_override
        if not can_submit:
            return JSONResponse(
                {
                    "status": "not_ready",
                    "error": {
                        "code": "WORKFLOW_NOT_READY",
                        "blockers": state["blockers"],
                    },
                },
                status_code=503,
            )

        call_id = spawn(body)
        run_id = str(uuid.uuid4())
        return {
            "run_id": run_id,
            "call_id": call_id,
            "status": "accepted",
            "result_url": f"/v1/runs/{call_id}",
        }

    @web.get("/v1/runs/{call_id}")
    async def get_result(call_id: str) -> Any:
        try:
            result = lookup(call_id)
            validate_instance(result, "output.json")
            return result
        except TimeoutError:
            return JSONResponse({"call_id": call_id, "status": "running"}, status_code=202)
        except Exception:
            return JSONResponse(
                {"call_id": call_id, "status": "failed", "error": {"code": "RUN_FAILED"}},
                status_code=500,
            )

    return web


@app.function(
    image=runtime_image,
    min_containers=0,
    max_containers=20,
    scaledown_window=2,
)
@modal.concurrent(max_inputs=20)
@modal.asgi_app(requires_proxy_auth=True)
def api() -> Any:
    return create_fastapi_app()
