"""Generated Modal runtime for the Japanese procedural sumi-e sample lane.

Generated by skill-to-modal/0.3.0. The renderer below is a slug-locked,
skill-owned resource. Change the reviewed source/profile/compiler, never this
generated container.
"""

from __future__ import annotations

import hashlib
import importlib
import json
import os
import re
import secrets
import shutil
import sys
import time
import uuid
from functools import lru_cache
from pathlib import Path
from typing import Any, Callable, Mapping

import modal
from jsonschema import Draft202012Validator


APP_NAME = "cognition-japanese-style-story-video"
WORKFLOW_VERSION = "japanese-style-story-video@0.2.0"
EXECUTION_KIND = "sample_media_pipeline"
LOCAL_ROOT = Path(__file__).resolve().parent
IMAGE_ROOT = Path("/root/japanese_style_story_video")
PUBLIC_BASE_URL = "https://omo-space--cognition-japanese-style-story-video-api.modal.run"
MEDIA_ARTIFACT_ROOT = Path(
    os.environ.get("OMO_MEDIA_ARTIFACT_ROOT", "/media-artifacts")
)
ARTIFACT_TTL_SECONDS = 3600
STYLE_ID = "sumi-e-awake-v3"
PUBLIC_STYLE = "sumi-e"
SAMPLE_ID = "sample-demello-10s"
PRICE_USD = 0.10
OWNER_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:@/-]{1,199}$")
RUN_RE = re.compile(r"^run-[0-9a-f]{32}$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
FILENAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$")


class WorkflowNotReady(RuntimeError):
    """Raised before effects when the reviewed sample executor is unavailable."""


class ArtifactAccessError(RuntimeError):
    """Typed owner or exact-object artifact denial."""


class DomainStateError(RuntimeError):
    """Typed owner-scoped run-state failure."""


def _asset_root() -> Path:
    return LOCAL_ROOT if (LOCAL_ROOT / "schemas" / "input.json").is_file() else IMAGE_ROOT


@lru_cache(maxsize=None)
def load_json(relative_path: str) -> dict[str, Any]:
    with (_asset_root() / relative_path).open(encoding="utf-8") as handle:
        value = json.load(handle)
    if not isinstance(value, dict):
        raise ValueError("reviewed JSON asset must contain an object")
    return value


@lru_cache(maxsize=None)
def load_schema(name: str) -> dict[str, Any]:
    schema = load_json(f"schemas/{name}")
    Draft202012Validator.check_schema(schema)
    return schema


def validate_instance(instance: Any, schema_name: str) -> None:
    Draft202012Validator(load_schema(schema_name)).validate(instance)


def readiness() -> dict[str, Any]:
    return load_json("manifest.json")["readiness"]


def _owner(value: str) -> str:
    if not isinstance(value, str) or not OWNER_RE.fullmatch(value):
        raise ArtifactAccessError("OWNER_INVALID")
    return value


def owner_scope(owner_id: str) -> str:
    owner = _owner(owner_id)
    return hashlib.sha256(("omo-owner-v1\0" + owner).encode()).hexdigest()[:24]


def access_token_sha256(access_token: str) -> str:
    if not isinstance(access_token, str) or len(access_token) < 32 or len(access_token) > 200:
        raise ArtifactAccessError("ACCESS_TOKEN_INVALID")
    return hashlib.sha256(("omo-artifact-access-v1\0" + access_token).encode()).hexdigest()


def run_id_for(owner_id: str, access_token: str) -> str:
    owner = _owner(owner_id)
    token_digest = access_token_sha256(access_token)
    digest = hashlib.sha256(
        ("omo-japanese-run-v1\0" + owner + "\0" + token_digest).encode()
    ).hexdigest()
    return "run-" + digest[:32]


class InMemoryDomainState:
    """Generated owner-scoped state seam; hosted work is polled by Modal call ID."""

    def __init__(self, clock: Callable[[], float] = time.time) -> None:
        self._clock = clock
        self._records: dict[str, dict[str, Any]] = {}

    def create(self, owner_id: str, run_id: str, ttl_seconds: int = 3600) -> dict[str, Any]:
        owner = _owner(owner_id)
        if not RUN_RE.fullmatch(run_id) or not 60 <= ttl_seconds <= 86400:
            raise DomainStateError("STATE_INPUT_INVALID")
        if run_id in self._records:
            record = self._records[run_id]
            if record["owner_id"] == owner:
                return self.read_owned(owner, run_id)
            raise DomainStateError("STATE_NOT_FOUND")
        now = float(self._clock())
        self._records[run_id] = {
            "run_id": run_id,
            "owner_id": owner,
            "status": "queued",
            "phase": "queued",
            "progress_pct": 0,
            "created_at": now,
            "updated_at": now,
            "expires_at": now + ttl_seconds,
        }
        return self.read_owned(owner, run_id)

    def transition(
        self, owner_id: str, run_id: str, status: str, phase: str, progress_pct: int
    ) -> dict[str, Any]:
        record = self._owned(owner_id, run_id)
        allowed = {"queued": {"processing"}, "processing": {"done", "blocked"}}
        if status not in allowed.get(record["status"], set()):
            raise DomainStateError("STATE_TRANSITION_INVALID")
        if not isinstance(progress_pct, int) or progress_pct < record["progress_pct"]:
            raise DomainStateError("STATE_PROGRESS_INVALID")
        if status == "done" and progress_pct != 100:
            raise DomainStateError("STATE_PROGRESS_INVALID")
        record.update(
            status=status,
            phase=str(phase)[:80],
            progress_pct=progress_pct,
            updated_at=float(self._clock()),
        )
        return self.read_owned(owner_id, run_id)

    def _owned(self, owner_id: str, run_id: str) -> dict[str, Any]:
        owner = _owner(owner_id)
        record = self._records.get(run_id)
        if record is None or record["owner_id"] != owner:
            raise DomainStateError("STATE_NOT_FOUND")
        if float(self._clock()) >= record["expires_at"]:
            raise DomainStateError("STATE_EXPIRED")
        return record

    def read_owned(self, owner_id: str, run_id: str) -> dict[str, Any]:
        record = self._owned(owner_id, run_id)
        return {
            key: value
            for key, value in record.items()
            if key != "owner_id"
        }


domain_state = InMemoryDomainState()


@lru_cache(maxsize=1)
def _demello_modules() -> tuple[Any, Any]:
    root = _asset_root()
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    workflow = importlib.import_module("resources.demello_resource.workflow")
    image_gen = importlib.import_module("resources.demello_resource.image_gen")
    return workflow, image_gen


def _canonical_json_bytes(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _artifact_descriptor(
    root: Path,
    owner_id: str,
    run_id: str,
    access_token: str,
    expires: int,
    source: Path,
    *,
    kind: str,
    content_type: str,
) -> dict[str, Any]:
    scope = owner_scope(owner_id)
    digest = _sha256_file(source)
    filename = source.name
    if not SHA256_RE.fullmatch(digest) or not FILENAME_RE.fullmatch(filename):
        raise ArtifactAccessError("ARTIFACT_DESCRIPTOR_INVALID")
    relative = Path("owners") / scope / "runs" / run_id / digest / filename
    destination = root / relative
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        if _sha256_file(destination) != digest:
            raise ArtifactAccessError("ARTIFACT_IMMUTABLE_COLLISION")
    else:
        try:
            os.link(source, destination)
        except OSError:
            shutil.copyfile(source, destination)
    url = (
        f"{PUBLIC_BASE_URL}/v1/artifacts/{scope}/{run_id}/{digest}/{filename}"
        f"?expires={expires}&access_token={access_token}"
    )
    return {
        "kind": kind,
        "object_key": relative.as_posix(),
        "sha256": digest,
        "bytes": destination.stat().st_size,
        "content_type": content_type,
        "url": url,
    }


def _write_access_manifest(
    root: Path,
    owner_id: str,
    run_id: str,
    access_token: str,
    expires: int,
    artifacts: list[dict[str, Any]],
) -> None:
    scope = owner_scope(owner_id)
    manifest = {
        "schema_version": "omo.owner-artifacts/v1",
        "owner_scope": scope,
        "run_id": run_id,
        "access_token_sha256": access_token_sha256(access_token),
        "expires": expires,
        "artifacts": {
            item["object_key"]: {
                "sha256": item["sha256"],
                "bytes": item["bytes"],
                "content_type": item["content_type"],
            }
            for item in artifacts
        },
    }
    path = root / "owners" / scope / "runs" / run_id / "access.json"
    temporary = path.with_name("access.json." + uuid.uuid4().hex + ".tmp")
    temporary.write_bytes(_canonical_json_bytes(manifest))
    os.replace(temporary, path)


def run_sample_pipeline(
    payload: dict[str, Any],
    *,
    owner_id: str,
    run_id: str,
    access_token: str,
    output_root: Path,
    clock: Callable[[], float] = time.time,
) -> dict[str, Any]:
    """Run the pinned sample through the reused reviewed renderer and QA."""
    validate_instance(payload, "input.json")
    if run_id != run_id_for(owner_id, access_token):
        raise ArtifactAccessError("RUN_OWNER_MISMATCH")
    workflow, _image_gen = _demello_modules()
    resource_root = _asset_root() / "resources" / "demello_resource"
    owner_root = output_root / "owners" / owner_scope(owner_id)
    reviewed_request = {
        "audio_ref": SAMPLE_ID,
        "style": STYLE_ID,
        "duration_bounds": {"min_seconds": 10, "max_seconds": 10},
        "run_id": run_id,
        "max_cost_usd": 0.003,
    }
    config = workflow.PipelineConfig(
        artifact_root=owner_root,
        work_root=Path("/tmp/omo-japanese-story-video"),
        audio_refs={SAMPLE_ID: resource_root / "assets" / "sample-demello-10s.m4a"},
        transcript_refs={
            SAMPLE_ID: resource_root / "assets" / "sample-demello-10s.transcript.json"
        },
        allow_procedural_fallback=True,
        anchor_interval_seconds=3,
        guarded_price_usd=PRICE_USD,
        static_estimate_usd=0.003,
    )
    rich = workflow.run_pipeline(reviewed_request, config)
    run_root = owner_root / "runs" / run_id
    transcript = load_json(
        "resources/demello_resource/assets/sample-demello-10s.transcript.json"
    )
    transcript_value = workflow._coerce_transcript(transcript, 10.0)
    frame_brief = workflow.deterministic_director(transcript_value, 10.0)
    generated_frames = rich["image_generation"]["frames"]
    frame_manifest = {
        "schema_version": "japanese.procedural-sumi-e-frames/v1",
        "style": PUBLIC_STYLE,
        "internal_style": STYLE_ID,
        "palette": {"paper": "#FFFFFF", "ink": "#1A1A1A"},
        "width": 1080,
        "height": 1920,
        "semantic_fps": 3,
        "frames": [
            {
                key: frame[key]
                for key in (
                    "frame_id",
                    "second",
                    "parent_frame_id",
                    "prompt_sha256",
                    "image_sha256",
                    "attempts",
                    "visual",
                )
            }
            for frame in generated_frames
        ],
    }
    (run_root / "transcript.json").write_bytes(_canonical_json_bytes(transcript))
    (run_root / "frame-brief.json").write_bytes(_canonical_json_bytes(frame_brief))
    (run_root / "frames.json").write_bytes(_canonical_json_bytes(frame_manifest))
    expires = int(clock()) + ARTIFACT_TTL_SECONDS
    declarations = [
        ("video", "video/mp4", run_root / "video.mp4"),
        ("contact_sheet", "image/jpeg", run_root / "contact-sheet.jpg"),
        ("transcript", "application/json", run_root / "transcript.json"),
        ("frame_brief", "application/json", run_root / "frame-brief.json"),
        ("frame_manifest", "application/json", run_root / "frames.json"),
    ]
    artifacts = [
        _artifact_descriptor(
            output_root,
            owner_id,
            run_id,
            access_token,
            expires,
            path,
            kind=kind,
            content_type=content_type,
        )
        for kind, content_type, path in declarations
    ]
    _write_access_manifest(
        output_root, owner_id, run_id, access_token, expires, artifacts
    )
    result = {
        "run_id": run_id,
        "status": "completed",
        "workflow_version": WORKFLOW_VERSION,
        "artifacts": artifacts,
        "media": {
            key: rich["media"][key]
            for key in (
                "duration_seconds",
                "width",
                "height",
                "fps",
                "video_codec",
                "audio_codec",
            )
        },
        "usage": {
            "generated_frames": len(generated_frames),
            "accepted_frames": len(generated_frames),
            "output_frames": rich["frames_used"]["output"],
            "generation_provider": "procedural-fallback",
            "provider_cost_usd": 0,
        },
    }
    validate_instance(result, "output.json")
    return result


Executor = Callable[[dict[str, Any]], dict[str, Any]]


def execute_workflow(
    payload: dict[str, Any],
    *,
    executor: Executor | None = None,
    owner_id: str = "local-owner",
    run_id: str | None = None,
    access_token: str | None = None,
    artifact_root: Path | None = None,
    clock: Callable[[], float] = time.time,
) -> dict[str, Any]:
    validate_instance(payload, "input.json")
    if executor is not None:
        result = executor(payload)
        validate_instance(result, "output.json")
        return result
    state = readiness()
    if not state["can_submit"]:
        raise WorkflowNotReady("; ".join(item["code"] for item in state["blockers"]))
    token = access_token or secrets.token_urlsafe(32)
    identifier = run_id or run_id_for(owner_id, token)
    root = artifact_root or MEDIA_ARTIFACT_ROOT
    result = run_sample_pipeline(
        payload,
        owner_id=owner_id,
        run_id=identifier,
        access_token=token,
        output_root=root,
        clock=clock,
    )
    if artifact_root is None:
        media_artifact_volume.commit()
    return result


runtime_image = (
    modal.Image.debian_slim(python_version="3.12")
    .apt_install("ffmpeg")
    .uv_pip_install(
        "modal==1.5.0",
        "fastapi==0.109.0",
        "jsonschema==4.26.0",
        "numpy==2.2.6",
        "Pillow==11.3.0",
    )
    .add_local_dir(LOCAL_ROOT / "schemas", IMAGE_ROOT / "schemas", copy=True)
    .add_local_dir(LOCAL_ROOT / "prompts", IMAGE_ROOT / "prompts", copy=True)
    .add_local_dir(LOCAL_ROOT / "resources", IMAGE_ROOT / "resources", copy=True)
    .add_local_file(
        LOCAL_ROOT / "manifest.json", str(IMAGE_ROOT / "manifest.json"), copy=True
    )
    .add_local_file(
        LOCAL_ROOT / "capability-manifest.json",
        str(IMAGE_ROOT / "capability-manifest.json"),
        copy=True,
    )
)

media_artifact_volume = modal.Volume.from_name(
    "omo-japanese-style-story-video-artifacts", create_if_missing=True
)
app = modal.App(APP_NAME)


@app.function(
    image=runtime_image,
    cpu=2.0,
    memory=2048,
    timeout=1200,
    min_containers=0,
    max_containers=2,
    scaledown_window=5,
    volumes={str(MEDIA_ARTIFACT_ROOT): media_artifact_volume},
)
def run_workflow(envelope: dict[str, Any]) -> dict[str, Any]:
    return execute_workflow(
        envelope["input"],
        owner_id=envelope["owner_id"],
        run_id=envelope["run_id"],
        access_token=envelope["access_token"],
    )


SpawnRunner = Callable[[dict[str, Any]], str]
LookupResult = Callable[[str], dict[str, Any]]


def create_fastapi_app(
    spawn_runner: SpawnRunner | None = None,
    lookup_result: LookupResult | None = None,
    *,
    ready_override: bool | None = None,
) -> Any:
    from fastapi import Body, FastAPI, Header, HTTPException, Query
    from fastapi.responses import JSONResponse, Response
    from jsonschema import ValidationError

    web = FastAPI(title="japanese-style-story-video", version="0.2.0")

    def default_spawn(envelope: dict[str, Any]) -> str:
        return run_workflow.spawn(envelope).object_id

    def default_lookup(call_id: str) -> dict[str, Any]:
        return modal.FunctionCall.from_id(call_id).get(timeout=0)

    spawn = spawn_runner or default_spawn
    lookup = lookup_result or default_lookup

    @web.post("/v1/runs", status_code=202)
    async def submit(
        body: Any = Body(...),
        x_omo_owner_id: str | None = Header(default=None, alias="X-Omo-Owner-Id"),
    ) -> Any:
        try:
            validate_instance(body, "input.json")
            owner_id = _owner(x_omo_owner_id or "")
        except (ValidationError, ArtifactAccessError) as exc:
            detail = exc.message if isinstance(exc, ValidationError) else "owner_required"
            raise HTTPException(status_code=422, detail=detail) from exc
        state = readiness()
        can_submit = state["can_submit"] if ready_override is None else ready_override
        if not can_submit:
            return JSONResponse(
                {
                    "status": "not_ready",
                    "error": {"code": "WORKFLOW_NOT_READY", "blockers": state["blockers"]},
                },
                status_code=503,
            )
        access_token = secrets.token_urlsafe(32)
        run_id = run_id_for(owner_id, access_token)
        domain_state.create(owner_id, run_id)
        call_id = spawn(
            {
                "input": body,
                "owner_id": owner_id,
                "run_id": run_id,
                "access_token": access_token,
            }
        )
        return {
            "run_id": run_id,
            "call_id": call_id,
            "status": "accepted",
            "phase": "queued",
            "progress_pct": 0,
            "result_url": (
                f"/v1/runs/{run_id}?call_id={call_id}&access_token={access_token}"
            ),
        }

    @web.get("/v1/runs/{run_id}")
    async def get_result(
        run_id: str,
        call_id: str = Query(..., min_length=8, max_length=200),
        access_token: str = Query(..., min_length=32, max_length=200),
        x_omo_owner_id: str | None = Header(default=None, alias="X-Omo-Owner-Id"),
    ) -> Any:
        owner_id = x_omo_owner_id or ""
        try:
            if run_id != run_id_for(owner_id, access_token):
                raise ArtifactAccessError("RUN_OWNER_MISMATCH")
        except ArtifactAccessError as exc:
            raise HTTPException(status_code=404, detail="run_not_found") from exc
        try:
            result = lookup(call_id)
            validate_instance(result, "output.json")
            if result["run_id"] != run_id:
                raise ValueError("run result identity mismatch")
            return result
        except TimeoutError:
            return JSONResponse(
                {"run_id": run_id, "status": "processing", "phase": "rendering"},
                status_code=202,
            )
        except Exception:
            return JSONResponse(
                {"run_id": run_id, "status": "failed", "error": {"code": "RUN_FAILED"}},
                status_code=500,
            )

    @web.get("/v1/artifacts/{scope}/{run_id}/{digest}/{filename}")
    async def get_artifact(
        scope: str,
        run_id: str,
        digest: str,
        filename: str,
        expires: int,
        access_token: str = Query(..., min_length=32, max_length=200),
    ) -> Any:
        try:
            if not re.fullmatch(r"[0-9a-f]{24}", scope):
                raise ArtifactAccessError("ARTIFACT_KEY_INVALID")
            if not RUN_RE.fullmatch(run_id) or not SHA256_RE.fullmatch(digest):
                raise ArtifactAccessError("ARTIFACT_KEY_INVALID")
            if not FILENAME_RE.fullmatch(filename) or expires < int(time.time()):
                raise ArtifactAccessError("ARTIFACT_LINK_EXPIRED")
        except ArtifactAccessError as exc:
            raise HTTPException(status_code=404, detail="artifact_not_found") from exc
        media_artifact_volume.reload()
        access_path = MEDIA_ARTIFACT_ROOT / "owners" / scope / "runs" / run_id / "access.json"
        try:
            access = json.loads(access_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise HTTPException(status_code=404, detail="artifact_not_found") from exc
        relative = (Path("owners") / scope / "runs" / run_id / digest / filename).as_posix()
        evidence = access.get("artifacts", {}).get(relative)
        if (
            access.get("owner_scope") != scope
            or access.get("run_id") != run_id
            or access.get("expires") != expires
            or access.get("access_token_sha256") != access_token_sha256(access_token)
            or not isinstance(evidence, Mapping)
            or evidence.get("sha256") != digest
        ):
            raise HTTPException(status_code=404, detail="artifact_not_found")
        path = MEDIA_ARTIFACT_ROOT / relative
        try:
            data = path.read_bytes()
        except OSError as exc:
            raise HTTPException(status_code=404, detail="artifact_not_found") from exc
        if hashlib.sha256(data).hexdigest() != digest or len(data) != evidence.get("bytes"):
            raise HTTPException(status_code=404, detail="artifact_not_found")
        return Response(
            content=data,
            media_type=str(evidence["content_type"]),
            headers={
                "Cache-Control": "private, no-store",
                "Content-Disposition": f'attachment; filename="{filename}"',
            },
        )

    return web


@app.function(
    image=runtime_image,
    min_containers=0,
    max_containers=20,
    scaledown_window=2,
    volumes={str(MEDIA_ARTIFACT_ROOT): media_artifact_volume},
)
@modal.concurrent(max_inputs=20)
@modal.asgi_app(requires_proxy_auth=True)
def api() -> Any:
    return create_fastapi_app()
