"""Generated Modal contract runtime for audio-symbolic-animation.

Generated by skill-to-modal/0.1.0; change the profile/compiler, not this file.
Complex or unapproved capabilities fail closed. Tests inject a pure mock
executor and never make provider calls.
"""

from __future__ import annotations

import json
import uuid
from functools import lru_cache
from pathlib import Path
from typing import Any, Callable

import modal
from jsonschema import Draft202012Validator


APP_NAME = 'cognition-audio-symbolic-animation'
WORKFLOW_VERSION = 'audio-symbolic-animation@0.1.0'
EXECUTION_KIND = 'complex_external'
LOCAL_ROOT = Path(__file__).resolve().parent
IMAGE_ROOT = Path('/root/audio_symbolic_animation')


class WorkflowNotReady(RuntimeError):
    """Raised before spend when the reviewed workflow cannot run live."""


def _asset_root() -> Path:
    return LOCAL_ROOT if (LOCAL_ROOT / "schemas" / "input.json").is_file() else IMAGE_ROOT


@lru_cache(maxsize=None)
def load_json(relative_path: str) -> dict[str, Any]:
    with (_asset_root() / relative_path).open(encoding="utf-8") as handle:
        return json.load(handle)


@lru_cache(maxsize=None)
def load_schema(name: str) -> dict[str, Any]:
    schema = load_json(f"schemas/{name}")
    Draft202012Validator.check_schema(schema)
    return schema


def validate_instance(instance: Any, schema_name: str) -> None:
    Draft202012Validator(load_schema(schema_name)).validate(instance)


def readiness() -> dict[str, Any]:
    return load_json("manifest.json")["readiness"]


Executor = Callable[[dict[str, Any]], dict[str, Any]]


def execute_workflow(
    payload: dict[str, Any], *, executor: Executor | None = None
) -> dict[str, Any]:
    """Validate, execute once, and validate output.

    A mock executor is an explicit offline test seam. The generated live
    candidate never substitutes mock artifacts for unavailable providers.
    """
    validate_instance(payload, "input.json")
    if executor is None:
        state = readiness()
        raise WorkflowNotReady(
            "; ".join(reason["code"] for reason in state["blockers"])
        )
    result = executor(payload)
    validate_instance(result, "output.json")
    return result


runtime_image = (
    modal.Image.debian_slim(python_version="3.12")
    .apt_install('ffmpeg')
    .uv_pip_install(
        "modal==1.5.0",
        "fastapi==0.109.0",
        "jsonschema==4.26.0",
    )
    .add_local_dir(LOCAL_ROOT / "schemas", IMAGE_ROOT / "schemas", copy=True)
    .add_local_dir(LOCAL_ROOT / "prompts", IMAGE_ROOT / "prompts", copy=True)
    .add_local_file(LOCAL_ROOT / "manifest.json", str(IMAGE_ROOT / "manifest.json"), copy=True)
)

app = modal.App(APP_NAME)


@app.function(
    image=runtime_image,
    cpu=4.0,
    memory=8192,
    timeout=14400,
    min_containers=0,
    max_containers=2,
    scaledown_window=5,
)
def run_workflow(payload: dict[str, Any]) -> dict[str, Any]:
    return execute_workflow(payload)


SpawnRunner = Callable[[dict[str, Any]], str]
LookupResult = Callable[[str], dict[str, Any]]


def create_fastapi_app(
    spawn_runner: SpawnRunner | None = None,
    lookup_result: LookupResult | None = None,
    *,
    ready_override: bool | None = None,
) -> Any:
    from fastapi import FastAPI, HTTPException
    from fastapi.responses import JSONResponse
    from jsonschema import ValidationError

    web = FastAPI(title='audio-symbolic-animation', version='0.1.0')

    def default_spawn(payload: dict[str, Any]) -> str:
        return run_workflow.spawn(payload).object_id

    def default_lookup(call_id: str) -> dict[str, Any]:
        return modal.FunctionCall.from_id(call_id).get(timeout=0)

    spawn = spawn_runner or default_spawn
    lookup = lookup_result or default_lookup

    @web.post("/v1/runs", status_code=202)
    async def submit(body: Any) -> Any:
        try:
            validate_instance(body, "input.json")
        except ValidationError as exc:
            raise HTTPException(status_code=422, detail=exc.message) from exc

        state = readiness()
        can_submit = state["can_submit"] if ready_override is None else ready_override
        if not can_submit:
            return JSONResponse(
                {
                    "status": "not_ready",
                    "error": {
                        "code": "WORKFLOW_NOT_READY",
                        "blockers": state["blockers"],
                    },
                },
                status_code=503,
            )

        call_id = spawn(body)
        run_id = str(uuid.uuid4())
        return {
            "run_id": run_id,
            "call_id": call_id,
            "status": "accepted",
            "result_url": f"/v1/runs/{call_id}",
        }

    @web.get("/v1/runs/{call_id}")
    async def get_result(call_id: str) -> Any:
        try:
            result = lookup(call_id)
            validate_instance(result, "output.json")
            return result
        except TimeoutError:
            return JSONResponse({"call_id": call_id, "status": "running"}, status_code=202)
        except Exception:
            return JSONResponse(
                {"call_id": call_id, "status": "failed", "error": {"code": "RUN_FAILED"}},
                status_code=500,
            )

    return web


@app.function(
    image=runtime_image,
    min_containers=0,
    max_containers=20,
    scaledown_window=2,
)
@modal.concurrent(max_inputs=20)
@modal.asgi_app(requires_proxy_auth=True)
def api() -> Any:
    return create_fastapi_app()
