"""Generated Modal contract runtime for decodable-book-maker.

Generated by skill-to-modal/0.6.0; change the profile/compiler, not this file.
Complex or unapproved capabilities fail closed. Tests inject a pure mock
executor and never make provider calls.
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
import uuid
import hashlib
import hmac
import time

from functools import lru_cache
from pathlib import Path
from typing import Any, Callable

import modal
from jsonschema import Draft202012Validator


APP_NAME = 'cognition-decodable-book-maker'
WORKFLOW_VERSION = 'decodable-book-maker@1.0.0'
EXECUTION_KIND = 'single_llm'
LOCAL_ROOT = Path(__file__).resolve().parent
IMAGE_ROOT = Path('/root/decodable_book_maker')
RENDER_ROOT = LOCAL_ROOT.parents[1] / "tools" / "render"
RESEARCH_ROOT = LOCAL_ROOT.parents[1] / "tools" / "research"



BOOK_ARTIFACT = {'cover_colors': {'playful': '#E8643B', 'classic': '#3E6B8F', 'warm': '#B45F4A'}, 'filename': 'decodable-book.pdf', 'footer': 'PhonicsMaker | A decodable reading book', 'signed_url_ttl_seconds': 3600, 'signing_key_env': 'LLM_API_KEY', 'subtitle': 'A stage-safe story for early readers', 'type': 'book_pdf', 'volume_name': 'omo-decodable-book-artifacts'}
ARTIFACT_ROOT = Path(os.environ.get("OMO_ARTIFACT_ROOT", "/artifacts"))
ARTIFACT_SIGNED_URL_TTL_SECONDS = 3600




class WorkflowNotReady(RuntimeError):
    """Raised before spend when the reviewed workflow cannot run live."""


class ProviderCallError(RuntimeError):
    """Safe provider failure code; response bodies and credentials are never logged."""


class InputAdapterError(ValueError):
    """Typed hostile-upload rejection raised before story generation."""


class ArtifactError(RuntimeError):
    """Typed PDF persistence/signing failure with no customer data in the message."""


def _asset_root() -> Path:
    return LOCAL_ROOT if (LOCAL_ROOT / "schemas" / "input.json").is_file() else IMAGE_ROOT


@lru_cache(maxsize=None)
def load_json(relative_path: str) -> dict[str, Any]:
    with (_asset_root() / relative_path).open(encoding="utf-8") as handle:
        return json.load(handle)


@lru_cache(maxsize=None)
def load_schema(name: str) -> dict[str, Any]:
    schema = load_json(f"schemas/{name}")
    Draft202012Validator.check_schema(schema)
    return schema


def validate_instance(instance: Any, schema_name: str) -> None:
    Draft202012Validator(load_schema(schema_name)).validate(instance)


def readiness() -> dict[str, Any]:
    return load_json("manifest.json")["readiness"]




def _book_renderer():
    try:
        from tools.render.book import pdf_page_count, render_book_pdf
    except ImportError:
        from omo_book_renderer import pdf_page_count, render_book_pdf
    return render_book_pdf, pdf_page_count


def _safe_run_component(value: str) -> str:
    if not re.fullmatch(r"run-[A-Za-z0-9_-]{4,120}", value):
        raise ArtifactError("ARTIFACT_RUN_ID_INVALID")
    return value


def _artifact_signature(secret_key: str, run_id: str, digest: str, filename: str, expires: int) -> str:
    message = f"GET\n{run_id}\n{digest}\n{filename}\n{expires}".encode("utf-8")
    return hmac.new(secret_key.encode("utf-8"), message, hashlib.sha256).hexdigest()


def _artifact_relative_url(run_id: str, digest: str, filename: str, *, signing_key: str, now: float) -> str:
    expires = int(now) + ARTIFACT_SIGNED_URL_TTL_SECONDS
    signature = _artifact_signature(signing_key, run_id, digest, filename, expires)
    return f"/v1/artifacts/{run_id}/{digest}/{filename}?expires={expires}&signature={signature}"


def materialize_book_artifact(
    result: dict[str, Any],
    input_value: dict[str, Any],
    *,
    output_root: Path | None = None,
    signing_key: str | None = None,
    clock: Callable[[], float] = time.time,
    commit: bool = False,
) -> dict[str, Any]:
    run_id = _safe_run_component(str(result.get("run_id") or ""))
    style_name = str(input_value.get("style") or "warm")
    cover_colors = BOOK_ARTIFACT["cover_colors"]
    cover_color = str(cover_colors.get(style_name) or cover_colors.get("warm") or "#B45F4A")
    manifest = {
        "schema_version": "omo.book-pdf/v1",
        "title": result["title"],
        "subtitle": BOOK_ARTIFACT["subtitle"],
        "book": result["book"],
        "page_plan": result["page_plan"],
        "style": {"name": style_name, "cover_color": cover_color},
        "footer": BOOK_ARTIFACT["footer"],
    }
    key = signing_key or os.environ.get(str(BOOK_ARTIFACT["signing_key_env"]), "")
    if not key:
        raise ArtifactError("ARTIFACT_SIGNING_KEY_MISSING")
    render_book_pdf, pdf_page_count = _book_renderer()
    data = render_book_pdf(manifest)
    digest = hashlib.sha256(data).hexdigest()
    filename = str(BOOK_ARTIFACT["filename"])
    root = output_root or ARTIFACT_ROOT
    relative = Path("runs") / run_id / digest / filename
    destination = root / relative
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        if destination.read_bytes() != data:
            raise ArtifactError("ARTIFACT_IMMUTABLE_COLLISION")
    else:
        with destination.open("xb") as stream:
            stream.write(data)
    if commit:
        artifact_volume.commit()
    descriptor = {
        "kind": "pdf",
        "role": "book",
        "object_key": relative.as_posix(),
        "filename": filename,
        "content_type": "application/pdf",
        "bytes": len(data),
        "sha256": digest,
        "page_count": pdf_page_count(data),
    }
    return {
        **result,
        "artifact": descriptor,
        "artifact_url": _artifact_relative_url(
            run_id, digest, filename, signing_key=key, now=clock()
        ),
    }








Executor = Callable[[dict[str, Any]], dict[str, Any]]
InputExtractor = Callable[[list[dict[str, str]]], Any]
FindingsWriter = Callable[[dict[str, Any]], Any]


def execute_workflow(
    payload: dict[str, Any],
    *,
    executor: Executor | None = None,
    input_extractor: InputExtractor | None = None,
    findings_writer: FindingsWriter | None = None,
    artifact_root: Path | None = None,
    artifact_signing_key: str | None = None,
    clock: Callable[[], float] | None = None,
) -> dict[str, Any]:
    """Validate, execute once, and validate output.

    A mock executor is an explicit offline test seam. The generated live
    candidate never substitutes mock artifacts for unavailable providers.
    """
    validate_instance(payload, "input.json")
    normalized_payload, adapter_responses = payload, []
    if executor is None:
        if findings_writer is None:
            state = readiness()
            if not state["can_submit"]:
                raise WorkflowNotReady(
                    "; ".join(reason["code"] for reason in state["blockers"])
                )
        raise WorkflowNotReady("LIVE_EXECUTOR_NOT_CONFIGURED")
    else:
        result = executor(normalized_payload)
    if "artifact" not in result or "artifact_url" not in result:
        result = materialize_book_artifact(
            result,
            normalized_payload,
            output_root=artifact_root,
            signing_key=artifact_signing_key,
            clock=clock or time.time,
            commit=artifact_root is None,
        )
    validate_instance(result, "output.json")
    return result


runtime_image = (
    modal.Image.debian_slim(python_version="3.12")
    .uv_pip_install(
        "modal==1.5.0",
        "fastapi==0.109.0",
        "jsonschema==4.26.0",
        "pypdf==5.7.0",
        "reportlab==4.4.3",
    )
    .add_local_dir(LOCAL_ROOT / "schemas", IMAGE_ROOT / "schemas", copy=True)
    .add_local_dir(LOCAL_ROOT / "prompts", IMAGE_ROOT / "prompts", copy=True)
    .add_local_file(LOCAL_ROOT / "manifest.json", str(IMAGE_ROOT / "manifest.json"), copy=True)
    .add_local_file(LOCAL_ROOT / "capability-manifest.json", str(IMAGE_ROOT / "capability-manifest.json"), copy=True)
    .add_local_file(RENDER_ROOT / "book.py", str(IMAGE_ROOT / "omo_book_renderer.py"), copy=True)
    
    
    
)

app = modal.App(APP_NAME)
artifact_volume = modal.Volume.from_name('omo-decodable-book-artifacts', create_if_missing=True)


@app.function(
    image=runtime_image,
    cpu=1.0,
    memory=512,
    timeout=180,
    min_containers=0,
    max_containers=4,
    scaledown_window=5,
    volumes={str(ARTIFACT_ROOT): artifact_volume},
)
def run_workflow(payload: dict[str, Any]) -> dict[str, Any]:
    return execute_workflow(payload)


SpawnRunner = Callable[[dict[str, Any]], str]
LookupResult = Callable[[str], dict[str, Any]]


def create_fastapi_app(
    spawn_runner: SpawnRunner | None = None,
    lookup_result: LookupResult | None = None,
    *,
    ready_override: bool | None = None,
) -> Any:
    from fastapi import Body, FastAPI, HTTPException
    from fastapi.responses import JSONResponse, Response
    from jsonschema import ValidationError

    web = FastAPI(title='decodable-book-maker', version='1.0.0')

    def default_spawn(payload: dict[str, Any]) -> str:
        return run_workflow.spawn(payload).object_id

    def default_lookup(call_id: str) -> dict[str, Any]:
        return modal.FunctionCall.from_id(call_id).get(timeout=0)

    spawn = spawn_runner or default_spawn
    lookup = lookup_result or default_lookup

    @web.post("/v1/runs", status_code=202)
    async def submit(body: Any = Body(...)) -> Any:
        try:
            validate_instance(body, "input.json")
        except ValidationError as exc:
            raise HTTPException(status_code=422, detail=exc.message) from exc
        

        state = readiness()
        can_submit = state["can_submit"] if ready_override is None else ready_override
        if not can_submit:
            return JSONResponse(
                {
                    "status": "not_ready",
                    "error": {
                        "code": "WORKFLOW_NOT_READY",
                        "blockers": state["blockers"],
                    },
                },
                status_code=503,
            )

        call_id = spawn(body)
        run_id = str(uuid.uuid4())
        return {
            "run_id": run_id,
            "call_id": call_id,
            "status": "accepted",
            "result_url": f"/v1/runs/{call_id}",
        }

    @web.get("/v1/runs/{call_id}")
    async def get_result(call_id: str) -> Any:
        try:
            result = lookup(call_id)
            validate_instance(result, "output.json")
            return result
        except TimeoutError:
            return JSONResponse({"call_id": call_id, "status": "running"}, status_code=202)
        except Exception:
            return JSONResponse(
                {"call_id": call_id, "status": "failed", "error": {"code": "RUN_FAILED"}},
                status_code=500,
            )


    @web.get("/v1/artifacts/{run_id}/{digest}/{filename}")
    async def get_artifact(
        run_id: str,
        digest: str,
        filename: str,
        expires: int,
        signature: str,
    ) -> Any:
        key = os.environ.get(str(BOOK_ARTIFACT["signing_key_env"]), "")
        now = int(time.time())
        if (
            not key
            or expires < now
            or expires > now + ARTIFACT_SIGNED_URL_TTL_SECONDS
            or not re.fullmatch(r"[0-9a-f]{64}", digest)
            or not re.fullmatch(r"[0-9a-f]{64}", signature)
            or filename != BOOK_ARTIFACT["filename"]
        ):
            raise HTTPException(status_code=403, detail="invalid_artifact_signature")
        try:
            safe_run_id = _safe_run_component(run_id)
        except ArtifactError as exc:
            raise HTTPException(status_code=404, detail="artifact_not_found") from exc
        expected = _artifact_signature(key, safe_run_id, digest, filename, expires)
        if not hmac.compare_digest(signature, expected):
            raise HTTPException(status_code=403, detail="invalid_artifact_signature")
        artifact_volume.reload()
        path = ARTIFACT_ROOT / "runs" / safe_run_id / digest / filename
        try:
            data = path.read_bytes()
        except OSError as exc:
            raise HTTPException(status_code=404, detail="artifact_not_found") from exc
        if hashlib.sha256(data).hexdigest() != digest:
            raise HTTPException(status_code=404, detail="artifact_not_found")
        return Response(
            content=data,
            media_type="application/pdf",
            headers={
                "Cache-Control": "private, no-store",
                "Content-Disposition": f'attachment; filename="{filename}"',
            },
        )


    return web


@app.function(
    image=runtime_image,
    min_containers=0,
    max_containers=20,
    scaledown_window=2,
    volumes={str(ARTIFACT_ROOT): artifact_volume},
)
@modal.concurrent(max_inputs=20)
@modal.asgi_app(requires_proxy_auth=True)
def api() -> Any:
    return create_fastapi_app()
