"""Generated Modal contract runtime for syllable-splitter-and-counter.

Generated by skill-to-modal/0.1.0; change the profile/compiler, not this file.
Complex or unapproved capabilities fail closed. Tests inject a pure mock
executor and never make provider calls.
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
import uuid
from functools import lru_cache
from pathlib import Path
from typing import Any, Callable

import modal
from jsonschema import Draft202012Validator


APP_NAME = 'cognition-syllable-splitter-and-counter'
WORKFLOW_VERSION = 'syllable-splitter-and-counter@0.1.0'
EXECUTION_KIND = 'single_llm'
LOCAL_ROOT = Path(__file__).resolve().parent
IMAGE_ROOT = Path('/root/syllable_splitter_and_counter')

LIVE_PROVIDER = 'opencode-go'
LIVE_BASE_URL_ENV = 'LLM_BASE_URL'
LIVE_MODEL_ENV = 'LLM_MODEL'
LIVE_API_KEY_ENV = 'LLM_API_KEY'
LIVE_DEFAULT_BASE_URL = 'https://opencode.ai/zen/go/v1'
LIVE_DEFAULT_MODEL = 'deepseek-v4-flash'
LIVE_PROMPT_PATH = 'prompts/run.txt'
LIVE_MAX_TOKENS = 1200
LIVE_TEMPERATURE = 0.2
LIVE_TIMEOUT_SECONDS = 120
LIVE_INPUT_RATE_PER_MILLION = 0.14
LIVE_OUTPUT_RATE_PER_MILLION = 0.28
LIVE_MODEL_OUTPUT_SCHEMA = {'$schema': 'https://json-schema.org/draft/2020-12/schema', 'type': 'object', 'additionalProperties': False, 'properties': {'items': {'type': 'array', 'minItems': 1, 'maxItems': 30, 'items': {'type': 'object', 'additionalProperties': False, 'properties': {'word': {'type': 'string', 'minLength': 1, 'maxLength': 80}, 'syllabified': {'type': 'string', 'minLength': 1, 'maxLength': 120}, 'syllable_count': {'type': 'integer', 'minimum': 1, 'maximum': 20}, 'ambiguity_note': {'type': 'string', 'maxLength': 240}}, 'required': ['word', 'syllabified', 'syllable_count', 'ambiguity_note']}}, 'warnings': {'type': 'array', 'items': {'type': 'string', 'minLength': 1, 'maxLength': 240}, 'maxItems': 8}}, 'required': ['items', 'warnings']}



class WorkflowNotReady(RuntimeError):
    """Raised before spend when the reviewed workflow cannot run live."""


class ProviderCallError(RuntimeError):
    """Safe provider failure code; response bodies and credentials are never logged."""


def _asset_root() -> Path:
    return LOCAL_ROOT if (LOCAL_ROOT / "schemas" / "input.json").is_file() else IMAGE_ROOT


@lru_cache(maxsize=None)
def load_json(relative_path: str) -> dict[str, Any]:
    with (_asset_root() / relative_path).open(encoding="utf-8") as handle:
        return json.load(handle)


@lru_cache(maxsize=None)
def load_schema(name: str) -> dict[str, Any]:
    schema = load_json(f"schemas/{name}")
    Draft202012Validator.check_schema(schema)
    return schema


def validate_instance(instance: Any, schema_name: str) -> None:
    Draft202012Validator(load_schema(schema_name)).validate(instance)


def readiness() -> dict[str, Any]:
    return load_json("manifest.json")["readiness"]


def _extract_json_object(value: str) -> dict[str, Any]:
    fenced = re.sub(r"^```(?:json)?\s*|\s*```$", "", value.strip(), flags=re.I)
    start = fenced.find("{")
    end = fenced.rfind("}")
    if start < 0 or end <= start:
        raise ValueError("provider output did not contain a JSON object")
    parsed = json.loads(fenced[start : end + 1])
    if not isinstance(parsed, dict):
        raise ValueError("provider output must be a JSON object")
    return parsed


def _provider_completion(payload: dict[str, Any]) -> dict[str, Any]:
    missing = [name for name in readiness()["required_env_names"] if not os.environ.get(name)]
    if missing:
        raise WorkflowNotReady("MISSING_REQUIRED_ENV:" + ",".join(sorted(missing)))

    base_url = os.environ[LIVE_BASE_URL_ENV].rstrip("/")
    if not base_url.startswith("https://"):
        raise WorkflowNotReady("LLM_BASE_URL_MUST_BE_HTTPS")
    model = os.environ[LIVE_MODEL_ENV]
    system_prompt = (_asset_root() / LIVE_PROMPT_PATH).read_text(encoding="utf-8").strip()
    user_prompt = "Run the reviewed workflow using only this JSON input:\n" + json.dumps(
        payload, ensure_ascii=False, sort_keys=True
    )
    request_body = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": LIVE_TEMPERATURE,
        "max_tokens": LIVE_MAX_TOKENS,
        "response_format": {"type": "json_object"},
        "thinking": {"type": "disabled"},
    }
    request = urllib.request.Request(
        base_url + "/chat/completions",
        data=json.dumps(request_body).encode("utf-8"),
        headers={
            "Authorization": "Bearer " + os.environ[LIVE_API_KEY_ENV],
            "Content-Type": "application/json",
            "User-Agent": "Omo-Skill-Runner/0.1",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=LIVE_TIMEOUT_SECONDS) as response:
            raw = response.read(2_000_001)
    except urllib.error.HTTPError as exc:
        raise ProviderCallError(f"LLM_HTTP_{exc.code}") from exc
    except (urllib.error.URLError, TimeoutError) as exc:
        raise ProviderCallError("LLM_UNAVAILABLE") from exc
    if len(raw) > 2_000_000:
        raise ProviderCallError("LLM_RESPONSE_TOO_LARGE")
    try:
        provider_response = json.loads(raw)
        content = provider_response["choices"][0]["message"]["content"]
        generated = _extract_json_object(str(content))
        Draft202012Validator(LIVE_MODEL_OUTPUT_SCHEMA).validate(generated)
    except Exception as exc:
        raise ProviderCallError("LLM_INVALID_OUTPUT") from exc

    usage = provider_response.get("usage") or {}
    prompt_tokens = max(0, int(usage.get("prompt_tokens") or 0))
    completion_tokens = max(0, int(usage.get("completion_tokens") or 0))
    estimated_cost = (
        prompt_tokens * LIVE_INPUT_RATE_PER_MILLION
        + completion_tokens * LIVE_OUTPUT_RATE_PER_MILLION
    ) / 1_000_000
    return {
        "run_id": "run-" + str(uuid.uuid4()),
        "status": "completed",
        "workflow_version": WORKFLOW_VERSION,
        **generated,
        "usage": {
            "provider": LIVE_PROVIDER,
            "model": str(provider_response.get("model") or model),
            "llm_calls": 1,
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "estimated_cost_usd": round(estimated_cost, 8),
        },
    }



Executor = Callable[[dict[str, Any]], dict[str, Any]]


def execute_workflow(
    payload: dict[str, Any], *, executor: Executor | None = None
) -> dict[str, Any]:
    """Validate, execute once, and validate output.

    A mock executor is an explicit offline test seam. The generated live
    candidate never substitutes mock artifacts for unavailable providers.
    """
    validate_instance(payload, "input.json")
    if executor is None:
        state = readiness()
        if not state["can_submit"]:
            raise WorkflowNotReady(
                "; ".join(reason["code"] for reason in state["blockers"])
            )
        executor = _provider_completion
    result = executor(payload)
    validate_instance(result, "output.json")
    return result


runtime_image = (
    modal.Image.debian_slim(python_version="3.12")
    .uv_pip_install(
        "modal==1.5.0",
        "fastapi==0.109.0",
        "jsonschema==4.26.0",
    )
    .add_local_dir(LOCAL_ROOT / "schemas", IMAGE_ROOT / "schemas", copy=True)
    .add_local_dir(LOCAL_ROOT / "prompts", IMAGE_ROOT / "prompts", copy=True)
    .add_local_file(LOCAL_ROOT / "manifest.json", str(IMAGE_ROOT / "manifest.json"), copy=True)
)

app = modal.App(APP_NAME)


@app.function(
    image=runtime_image,
    cpu=1,
    memory=512,
    timeout=180,
    min_containers=0,
    max_containers=4,
    scaledown_window=5,
    secrets=[modal.Secret.from_name('omo-skill-providers')],
)
def run_workflow(payload: dict[str, Any]) -> dict[str, Any]:
    return execute_workflow(payload)


SpawnRunner = Callable[[dict[str, Any]], str]
LookupResult = Callable[[str], dict[str, Any]]


def create_fastapi_app(
    spawn_runner: SpawnRunner | None = None,
    lookup_result: LookupResult | None = None,
    *,
    ready_override: bool | None = None,
) -> Any:
    from fastapi import Body, FastAPI, HTTPException
    from fastapi.responses import JSONResponse
    from jsonschema import ValidationError

    web = FastAPI(title='syllable-splitter-and-counter', version='0.1.0')

    def default_spawn(payload: dict[str, Any]) -> str:
        return run_workflow.spawn(payload).object_id

    def default_lookup(call_id: str) -> dict[str, Any]:
        return modal.FunctionCall.from_id(call_id).get(timeout=0)

    spawn = spawn_runner or default_spawn
    lookup = lookup_result or default_lookup

    @web.post("/v1/runs", status_code=202)
    async def submit(body: Any = Body(...)) -> Any:
        try:
            validate_instance(body, "input.json")
        except ValidationError as exc:
            raise HTTPException(status_code=422, detail=exc.message) from exc

        state = readiness()
        can_submit = state["can_submit"] if ready_override is None else ready_override
        if not can_submit:
            return JSONResponse(
                {
                    "status": "not_ready",
                    "error": {
                        "code": "WORKFLOW_NOT_READY",
                        "blockers": state["blockers"],
                    },
                },
                status_code=503,
            )

        call_id = spawn(body)
        run_id = str(uuid.uuid4())
        return {
            "run_id": run_id,
            "call_id": call_id,
            "status": "accepted",
            "result_url": f"/v1/runs/{call_id}",
        }

    @web.get("/v1/runs/{call_id}")
    async def get_result(call_id: str) -> Any:
        try:
            result = lookup(call_id)
            validate_instance(result, "output.json")
            return result
        except TimeoutError:
            return JSONResponse({"call_id": call_id, "status": "running"}, status_code=202)
        except Exception:
            return JSONResponse(
                {"call_id": call_id, "status": "failed", "error": {"code": "RUN_FAILED"}},
                status_code=500,
            )

    return web


@app.function(
    image=runtime_image,
    min_containers=0,
    max_containers=20,
    scaledown_window=2,
)
@modal.concurrent(max_inputs=20)
@modal.asgi_app(requires_proxy_auth=True)
def api() -> Any:
    return create_fastapi_app()
