"""Generated Modal contract runtime for Gemini Ticket Priority Canary.

Generated by skill-to-modal/0.7.0; change the profile/compiler, not this file.
Complex or unapproved capabilities fail closed. Tests inject a pure mock
executor and never make provider calls.
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
import uuid

from functools import lru_cache
from pathlib import Path
from typing import Any, Callable

import modal
from jsonschema import Draft202012Validator


APP_NAME = 'cognition-gemini-ticket-priority-canary'
WORKFLOW_VERSION = 'gemini-ticket-priority-canary@1.0.0'
EXECUTION_KIND = 'single_llm'
LOCAL_ROOT = Path(__file__).resolve().parent
IMAGE_ROOT = Path('/root/gemini_ticket_priority_canary')
REPOSITORY_ROOT = LOCAL_ROOT.parents[1] if len(LOCAL_ROOT.parents) > 1 else LOCAL_ROOT
RENDER_ROOT = REPOSITORY_ROOT / "tools" / "render"
RESEARCH_ROOT = REPOSITORY_ROOT / "tools" / "research"

LIVE_PROVIDER = 'gemini'
LIVE_BASE_URL_ENV = 'GEMINI_BASE_URL'
LIVE_MODEL_ENV = 'GEMINI_MODEL'
LIVE_API_KEY_ENV = 'GEMINI_API_KEY'
LIVE_DEFAULT_BASE_URL = 'https://generativelanguage.googleapis.com/v1beta/openai'
LIVE_DEFAULT_MODEL = 'gemini-2.5-flash'
LIVE_PROMPT_PATH = 'prompts/system.txt'
LIVE_WORKFLOW_INSTRUCTIONS_PATH = 'prompts/workflow.txt'
LIVE_MAX_TOKENS = 1200
LIVE_MAX_INPUT_BYTES = 16384
LIVE_TEMPERATURE = 0.2
LIVE_TIMEOUT_SECONDS = 120
LIVE_INPUT_RATE_PER_MILLION = 0.3
LIVE_OUTPUT_RATE_PER_MILLION = 2.5
LIVE_MODEL_OUTPUT_SCHEMA = {'additionalProperties': False, 'properties': {'label': {'enum': ['high', 'low', 'medium'], 'maxLength': 6, 'minLength': 3, 'type': 'string'}, 'reason': {'maxLength': 240, 'minLength': 10, 'type': 'string'}}, 'required': ['label', 'reason'], 'type': 'object'}
SEMANTIC_NORMALIZERS = {}
SEMANTIC_EVIDENCE_SPEC = {'kind': 'schema_only', 'version': 1}






class WorkflowNotReady(RuntimeError):
    """Raised before spend when the reviewed workflow cannot run live."""


class ProviderCallError(RuntimeError):
    """Safe provider failure code; response bodies and credentials are never logged."""


class InputAdapterError(ValueError):
    """Typed hostile-upload rejection raised before story generation."""


class ArtifactError(RuntimeError):
    """Typed PDF persistence/signing failure with no customer data in the message."""


def _asset_root() -> Path:
    return LOCAL_ROOT if (LOCAL_ROOT / "schemas" / "input.json").is_file() else IMAGE_ROOT


@lru_cache(maxsize=None)
def load_json(relative_path: str) -> dict[str, Any]:
    with (_asset_root() / relative_path).open(encoding="utf-8") as handle:
        return json.load(handle)


@lru_cache(maxsize=None)
def load_schema(name: str) -> dict[str, Any]:
    schema = load_json(f"schemas/{name}")
    Draft202012Validator.check_schema(schema)
    return schema


def validate_instance(instance: Any, schema_name: str) -> None:
    Draft202012Validator(load_schema(schema_name)).validate(instance)


def readiness() -> dict[str, Any]:
    return load_json("manifest.json")["readiness"]



def _extract_json_object(value: str) -> dict[str, Any]:
    fenced = re.sub(r"^```(?:json)?\s*|\s*```$", "", value.strip(), flags=re.I)
    parsed = json.loads(fenced)
    if not isinstance(parsed, dict):
        raise ValueError("provider output must be a JSON object")
    return parsed


_ALIAS_GROUPS = (
    {"count", "number", "total"},
    {"input", "text", "source"},
    {"text", "digraph", "grapheme", "pattern"},
    {"word", "token"},
    {"syllabified", "syllables", "split"},
    {"ambiguity", "ambiguity_note", "note", "notes"},
    {"possible_confusions", "confusion_labels", "confusions", "labels"},
    {"practice_suggestions", "practice_ideas", "practice"},
    {"observation", "hypothesis"},
    {"premise", "story", "story_idea", "logline"},
    {"writing_hook", "hook"},
    {"rules_explanation", "rules", "explanation"},
    {"example_words", "examples"},
    {"target_words", "words"},
    {"sight_or_irregular_words", "sight_words", "irregular_words"},
    {"matched_phonemes", "phonemes"},
    {"target_position", "position"},
    {"pronunciation_note", "note", "notes"},
    {"rule", "phonics_rule", "phonics_pattern", "pattern"},
    {"constraints_used", "constraints"},
)


def _key_tokens(value: str) -> set[str]:
    words = re.findall(r"[a-z0-9]+", re.sub(r"([a-z])([A-Z])", r"\1_\2", value).lower())
    return {word[:-1] if word.endswith("s") and len(word) > 3 else word for word in words}


def _schema_types(schema: dict[str, Any]) -> set[str]:
    declared = schema.get("type")
    if isinstance(declared, str):
        return {declared}
    if isinstance(declared, list):
        return {str(item) for item in declared}
    if "const" in schema:
        value = schema["const"]
        if isinstance(value, bool):
            return {"boolean"}
        if isinstance(value, int):
            return {"integer"}
        if isinstance(value, str):
            return {"string"}
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return _schema_types({"const": schema["enum"][0]})
    return set()


def _value_type(value: Any) -> str:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    return "null"


def _alias_score(source: str, target: str, value: Any, schema: dict[str, Any]) -> int:
    if source == target:
        return 1000
    source_tokens = _key_tokens(source)
    target_tokens = _key_tokens(target)
    score = 0
    if source_tokens and target_tokens:
        overlap = source_tokens & target_tokens
        if overlap:
            score = max(score, 72 + 4 * len(overlap))
        if source_tokens <= target_tokens or target_tokens <= source_tokens:
            score = max(score, 82)
    for group in _ALIAS_GROUPS:
        group_tokens = set().union(*(_key_tokens(item) for item in group))
        if source_tokens & group_tokens and target_tokens & group_tokens:
            score = max(score, 68)
    expected = _schema_types(schema)
    actual = _value_type(value)
    if actual in expected or (actual == "integer" and "number" in expected):
        score += 8
    elif expected:
        coercible = actual == "string" and (
            "array" in expected
            or ("integer" in expected and bool(re.fullmatch(r"[-+]?\d+", value.strip())))
            or ("number" in expected and bool(re.fullmatch(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)", value.strip())))
            or ("boolean" in expected and value.strip().lower() in {"true", "false", "yes", "no", "1", "0"})
        )
        if not coercible:
            score -= 30
    return score


def _default_required(
    name: str,
    schema: dict[str, Any],
    context: dict[str, Any],
    repaired: dict[str, Any],
) -> tuple[bool, Any]:
    if "const" in schema:
        return True, schema["const"]
    if name == "type":
        requested = context.get("digraph_type")
        if requested in {"consonant", "vowel"}:
            return True, requested
        text = str(repaired.get("text") or "").lower()
        vowel_digraphs = {"ai", "au", "aw", "ay", "ea", "ee", "ew", "ie", "oa", "oe", "oi", "oo", "ou", "ow", "oy", "ue", "ui"}
        if text:
            return True, "vowel" if text in vowel_digraphs else "consonant"
    candidates = sorted(
        (
            (_alias_score(source, name, value, schema), source, value)
            for source, value in context.items()
        ),
        reverse=True,
    )
    if candidates and candidates[0][0] >= 68:
        return True, candidates[0][2]
    if name.endswith("_count"):
        prefix = _key_tokens(name.removesuffix("_count"))
        for sibling, value in repaired.items():
            if isinstance(value, list) and prefix & _key_tokens(sibling):
                return True, len(value)
    if name == "word" and isinstance(context.get("text"), str):
        start, end = repaired.get("start"), repaired.get("end")
        if isinstance(start, int) and isinstance(end, int):
            source_text = context["text"]
            left, right = start, end
            while left > 0 and (source_text[left - 1].isalnum() or source_text[left - 1] in "'-"):
                left -= 1
            while right < len(source_text) and (source_text[right].isalnum() or source_text[right] in "'-"):
                right += 1
            if left < right:
                return True, source_text[left:right]
    if name == "target_position":
        word = str(repaired.get("word") or "").lower()
        matches = repaired.get("matched_phonemes")
        if word and isinstance(matches, list):
            positions: set[str] = set()
            for match in matches:
                needle = str(match).lower()
                index = word.find(needle)
                if index < 0:
                    continue
                if word.find(needle, index + 1) >= 0:
                    positions.add("multiple")
                elif index == 0:
                    positions.add("initial")
                elif index + len(needle) == len(word):
                    positions.add("final")
                else:
                    positions.add("medial")
            if positions:
                return True, sorted(positions)[0] if len(positions) == 1 else "multiple"
    if name == "target_words":
        source = context.get("__generated__")
        coverage = source.get("coverage") if isinstance(source, dict) else None
        sentence = str(repaired.get("text") or "").lower()
        if isinstance(coverage, dict) and sentence:
            words: list[str] = []
            for covered in coverage.values():
                if not isinstance(covered, list):
                    continue
                for word in covered:
                    text = str(word)
                    if re.search(r"(?<![A-Za-z])" + re.escape(text.lower()) + r"(?![A-Za-z])", sentence):
                        words.append(text)
            if words:
                return True, words
    if name == "explanation" and isinstance(repaired.get("observation"), str):
        return True, repaired["observation"]
    if name == "uncertainty":
        dialect = str(context.get("dialect") or "the selected dialect")
        return True, f"Pronunciation may vary by speaker in {dialect}; review before teaching."
    if name in {"note", "pronunciation_note"}:
        dialect = str(context.get("dialect") or "the selected dialect")
        return True, f"Review this example in {dialect}."
    if name == "ambiguity_note":
        return True, ""
    if name == "writing_hook" and isinstance(repaired.get("premise"), str):
        premise = repaired["premise"].strip()
        if premise:
            return True, ("What happens next? " + premise)[:240]
    expected = _schema_types(schema)
    if "array" in expected and int(schema.get("minItems", 0)) == 0:
        return True, []
    if "string" in expected and int(schema.get("minLength", 0)) == 0:
        return True, ""
    if "object" in expected and not schema.get("required"):
        return True, {}
    return False, None


def _coerce_to_schema(value: Any, schema: dict[str, Any], context: dict[str, Any]) -> Any:
    expected = _schema_types(schema)
    if "object" in expected:
        properties = schema.get("properties") if isinstance(schema.get("properties"), dict) else {}
        if not isinstance(value, dict):
            seed: dict[str, Any] = {}
            for preferred in ("text", "word", "answer", "title", "premise", "value"):
                if preferred in properties:
                    seed[preferred] = value
                    break
            value = seed
        repaired: dict[str, Any] = {}
        used_sources: set[str] = set()
        for name, child_schema in properties.items():
            if name in value:
                repaired[name] = _coerce_to_schema(value[name], child_schema, context)
                used_sources.add(name)
        for source, child_value in value.items():
            if source in used_sources:
                continue
            choices = sorted(
                (
                    (_alias_score(source, target, child_value, child_schema), target, child_schema)
                    for target, child_schema in properties.items()
                    if target not in repaired
                ),
                reverse=True,
            )
            if choices and choices[0][0] >= 68:
                _, target, child_schema = choices[0]
                repaired[target] = _coerce_to_schema(child_value, child_schema, context)
        for name in schema.get("required", []):
            if name in repaired or name not in properties:
                continue
            found, default = _default_required(name, properties[name], context, repaired)
            if found:
                repaired[name] = _coerce_to_schema(default, properties[name], context)
        for name, child_schema in properties.items():
            allowed = child_schema.get("enum") if isinstance(child_schema, dict) else None
            if name in repaired and isinstance(allowed, list) and repaired[name] not in allowed:
                found, default = _default_required(name, child_schema, context, repaired)
                if found:
                    repaired[name] = _coerce_to_schema(default, child_schema, context)
        return repaired
    if "array" in expected:
        item_schema = schema.get("items") if isinstance(schema.get("items"), dict) else {}
        if isinstance(value, dict) and "object" not in _schema_types(item_schema):
            value = list(value)
        elif not isinstance(value, list):
            if isinstance(value, str) and re.search(r"[,;\n]", value):
                value = [part.strip() for part in re.split(r"[,;\n]+", value) if part.strip()]
            else:
                value = [value]
        repaired_items = [_coerce_to_schema(item, item_schema, context) for item in value]
        if schema.get("uniqueItems"):
            unique: list[Any] = []
            seen: set[str] = set()
            for item in repaired_items:
                marker = json.dumps(item, ensure_ascii=False, sort_keys=True)
                if marker not in seen:
                    seen.add(marker)
                    unique.append(item)
            repaired_items = unique
        maximum = schema.get("maxItems")
        return repaired_items[: int(maximum)] if isinstance(maximum, int) else repaired_items
    if "integer" in expected:
        if isinstance(value, str) and re.fullmatch(r"[-+]?\d+", value.strip()):
            return int(value.strip())
        if isinstance(value, float) and value.is_integer():
            return int(value)
        return value
    if "number" in expected:
        if isinstance(value, str):
            try:
                return float(value.strip())
            except ValueError:
                return value
        return value
    if "boolean" in expected and isinstance(value, str):
        if value.strip().lower() in {"true", "yes", "1"}:
            return True
        if value.strip().lower() in {"false", "no", "0"}:
            return False
    if "string" in expected:
        if value is None and int(schema.get("minLength", 0)) == 0:
            value = ""
        elif isinstance(value, list) and all(not isinstance(item, (dict, list)) for item in value):
            value = ", ".join(str(item) for item in value)
        elif not isinstance(value, str) and value is not None:
            value = str(value)
        maximum = schema.get("maxLength")
        if isinstance(value, str) and isinstance(maximum, int):
            value = value[:maximum]
        minimum = schema.get("minLength")
        if isinstance(value, str) and isinstance(minimum, int) and len(value) < minimum:
            suffix = " Review the supplied context and dialect before teaching."
            value = (value + suffix)[: int(schema.get("maxLength", len(value) + len(suffix)))]
    return value


def _repair_to_schema(
    generated: dict[str, Any], schema: dict[str, Any], prompt_input: dict[str, Any]
) -> dict[str, Any]:
    context = dict(prompt_input)
    context["__generated__"] = generated
    repaired = _coerce_to_schema(generated, schema, context)
    return repaired if isinstance(repaired, dict) else {}


def _strip_output_path(value: Any, path: list[str]) -> None:
    if not path:
        return
    part = path[0]
    if part == "*":
        if isinstance(value, list):
            for item in value:
                _strip_output_path(item, path[1:])
        return
    if not isinstance(value, dict) or part not in value:
        return
    if len(path) == 1:
        value.pop(part, None)
        return
    _strip_output_path(value[part], path[1:])


def _output_path_exists(value: Any, path: list[str]) -> bool:
    if not path:
        return True
    part = path[0]
    if part == "*":
        return isinstance(value, list) and any(_output_path_exists(item, path[1:]) for item in value)
    return isinstance(value, dict) and part in value and _output_path_exists(value[part], path[1:])


def _containing_word(source: str, start: int, end: int) -> str:
    left, right = start, end
    while left > 0 and (source[left - 1].isalnum() or source[left - 1] in "'-"):
        left -= 1
    while right < len(source) and (source[right].isalnum() or source[right] in "'-"):
        right += 1
    return source[left:right]


def _reviewed_digraph_occurrences(
    payload: dict[str, Any], generated: dict[str, Any]
) -> list[dict[str, Any]]:
    config = SEMANTIC_NORMALIZERS.get("digraph_spans")
    if not isinstance(config, dict):
        return []
    source = str(payload.get("text") or "")
    requested = str(payload.get("digraph_type") or "all")
    include_explanations = payload.get("include_explanations") is not False
    prose: dict[tuple[str, str], list[str]] = {}
    for item in generated.get("occurrences", []):
        if not isinstance(item, dict):
            continue
        explanation = item.get("explanation")
        token = str(item.get("text") or "").lower()
        word = str(item.get("word") or "").lower()
        if include_explanations and isinstance(explanation, str) and explanation.strip() and token:
            prose.setdefault((token, word), []).append(explanation)

    kinds = ("consonant", "vowel") if requested == "all" else (requested,)
    occurrences: list[dict[str, Any]] = []
    seen: set[tuple[int, int, str]] = set()
    lower_source = source.lower()
    for kind in kinds:
        reviewed = config.get(kind, [])
        if not isinstance(reviewed, list):
            continue
        for raw_token in reviewed:
            token = str(raw_token).lower()
            if not token:
                continue
            start = 0
            while True:
                start = lower_source.find(token, start)
                if start < 0:
                    break
                end = start + len(token)
                marker = (start, end, kind)
                if marker not in seen:
                    seen.add(marker)
                    word = _containing_word(source, start, end)
                    occurrence: dict[str, Any] = {
                        "text": source[start:end],
                        "word": word,
                        "start": start,
                        "end": end,
                        "type": kind,
                    }
                    available = prose.get((token, word.lower()), [])
                    if include_explanations and available:
                        occurrence["explanation"] = available.pop(0)
                    occurrences.append(occurrence)
                start += 1
    return sorted(
        occurrences,
        key=lambda item: (item["start"], item["end"], item["type"], item["text"].lower()),
    )


def _variant_index(word: str, variant: str) -> tuple[int, int] | None:
    clean_word = re.sub(r"[^a-z]", "", word.lower())
    clean_variant = variant.lower()
    if "_" in clean_variant:
        pieces = [re.sub(r"[^a-z]", "", piece) for piece in clean_variant.split("_")]
        pieces = [piece for piece in pieces if piece]
        if not pieces:
            return None
        match = re.search(".*?".join(re.escape(piece) for piece in pieces), clean_word)
        return (match.start(), match.end()) if match else None
    needle = re.sub(r"[^a-z]", "", clean_variant)
    start = clean_word.find(needle) if needle else -1
    return (start, start + len(needle)) if start >= 0 else None


def _matching_requested_phonemes(
    word: str, requested: list[str], phoneme_map: dict[str, Any]
) -> tuple[list[str], list[tuple[int, int]]]:
    matched: list[str] = []
    spans: list[tuple[int, int]] = []
    for raw_phoneme in requested:
        phoneme = str(raw_phoneme)
        variants = phoneme_map.get(phoneme.lower(), [phoneme])
        if not isinstance(variants, list):
            variants = [phoneme]
        found = next(
            (span for variant in variants if (span := _variant_index(word, str(variant))) is not None),
            None,
        )
        if found is not None:
            matched.append(phoneme)
            spans.append(found)
    return matched, spans


def _matches_reviewed_word_shape(word: str, shape: str) -> bool:
    clean_word = re.sub(r"[^a-z]", "", word.lower())
    reviewed_shape = shape.upper()
    if len(clean_word) != len(reviewed_shape):
        return False
    vowels = set("aeiou")
    return all(
        (symbol == "V" and letter in vowels)
        or (symbol == "C" and letter not in vowels)
        for letter, symbol in zip(clean_word, reviewed_shape)
    )


def _matches_reviewed_pattern(
    word: str, pattern: str, config: dict[str, Any]
) -> bool:
    shapes = config.get("pattern_to_word_shape", {})
    if isinstance(shapes, dict):
        shape = shapes.get(pattern)
        if isinstance(shape, str) and _matches_reviewed_word_shape(word, shape):
            return True
    graphemes = config.get("pattern_to_graphemes", {})
    if not isinstance(graphemes, dict):
        return False
    variants = graphemes.get(pattern, [])
    if not isinstance(variants, list):
        variants = [variants]
    clean_word = re.sub(r"[^a-z]", "", word.lower())
    for raw_variant in variants:
        variant = str(raw_variant).lower()
        if "_" not in variant and _variant_index(word, variant) is not None:
            return True
        pieces = [re.sub(r"[^a-z]", "", piece) for piece in variant.split("_")]
        if len(pieces) == 2 and all(pieces):
            pattern_re = re.escape(pieces[0]) + r"[^aeiou]*" + re.escape(pieces[1]) + "$"
            if re.search(pattern_re, clean_word):
                return True
    return False


def _target_in_sentence(sentence: str, target: str) -> bool:
    return bool(
        re.search(
            r"(?<![A-Za-z])" + re.escape(target) + r"(?![A-Za-z])",
            sentence,
            flags=re.I,
        )
    )


def _normalize_target_word_containment(
    generated: dict[str, Any], payload: dict[str, Any]
) -> None:
    config = SEMANTIC_NORMALIZERS.get("target_word_containment")
    if not isinstance(config, dict):
        return
    request_field = str(config.get("request_field") or "phonics_patterns")
    items_field = str(config.get("items_field") or "sentences")
    target_field = str(config.get("target_field") or "target_words")
    requested = [str(item) for item in payload.get(request_field, [])]
    removed = 0
    covered: set[str] = set()
    for item in generated.get(items_field, []):
        if not isinstance(item, dict):
            continue
        sentence = str(item.get("text") or "")
        kept: list[str] = []
        seen: set[str] = set()
        for raw_word in item.get(target_field, []):
            word = str(raw_word)
            matched = [
                pattern
                for pattern in requested
                if _matches_reviewed_pattern(word, pattern, config)
            ]
            marker = word.casefold()
            if matched and _target_in_sentence(sentence, word) and marker not in seen:
                kept.append(word)
                seen.add(marker)
                covered.update(matched)
            else:
                removed += 1
        item[target_field] = kept
    generated["coverage"] = [pattern for pattern in requested if pattern in covered]
    if removed:
        _append_bounded_warning(
            generated,
            f"Removed {removed} target word{'s' if removed != 1 else ''} without a reviewed spelling for the requested patterns.",
        )


def _phoneme_target_position(word: str, spans: list[tuple[int, int]]) -> str:
    clean_length = len(re.sub(r"[^a-z]", "", word.lower()))
    if len(spans) != 1:
        return "multiple"
    start, end = spans[0]
    if start == 0:
        return "initial"
    if end == clean_length:
        return "final"
    return "medial"


def _append_bounded_warning(generated: dict[str, Any], warning: str) -> None:
    schema = LIVE_MODEL_OUTPUT_SCHEMA.get("properties", {}).get("warnings", {})
    maximum = int(schema.get("maxItems", 0))
    if maximum <= 0:
        return
    warnings = [str(item) for item in generated.get("warnings", []) if str(item).strip()]
    if warning in warnings:
        generated["warnings"] = warnings[:maximum]
        return
    generated["warnings"] = (warnings[: maximum - 1] + [warning]) if len(warnings) >= maximum else warnings + [warning]


def _normalize_phoneme_containment(
    generated: dict[str, Any], payload: dict[str, Any]
) -> None:
    config = SEMANTIC_NORMALIZERS.get("phoneme_containment")
    if not isinstance(config, dict):
        return
    requested = [str(item) for item in payload.get("phonemes", [])]
    phoneme_map = config.get("phoneme_to_graphemes", {})
    if not isinstance(phoneme_map, dict):
        phoneme_map = {}
    denylist = {
        re.sub(r"[^a-z]", "", str(item).lower())
        for item in config.get("weak_evidence_denylist", [])
        if str(item).strip()
    }
    kept: list[dict[str, Any]] = []
    seen_words: set[str] = set()
    removed = 0
    for item in generated.get("words", []):
        if not isinstance(item, dict):
            removed += 1
            continue
        word = str(item.get("word") or "")
        marker = re.sub(r"[^a-z]", "", word.lower())
        if marker in denylist or marker in seen_words:
            removed += 1
            continue
        matched, spans = _matching_requested_phonemes(word, requested, phoneme_map)
        if not matched:
            removed += 1
            continue
        item["matched_phonemes"] = matched
        item["target_position"] = _phoneme_target_position(word, spans)
        kept.append(item)
        seen_words.add(marker)
    generated["words"] = kept
    generated["coverage"] = [
        phoneme
        for phoneme in requested
        if any(phoneme in item.get("matched_phonemes", []) for item in kept)
    ]
    if removed:
        _append_bounded_warning(
            generated,
            f"Removed {removed} word{'s' if removed != 1 else ''} without reviewed target evidence for the requested phonemes.",
        )


def _syllable_parts_for_spelling(
    syllabified: str, word: str, separator_chars: set[str]
) -> tuple[list[str], list[str]] | None:
    if not syllabified or not word:
        return None
    parts = [""]
    boundaries: list[str] = []
    word_index = 0
    for character in syllabified:
        if word_index < len(word) and character == word[word_index]:
            parts[-1] += character
            word_index += 1
        elif character in separator_chars and parts[-1] and word_index < len(word):
            boundaries.append(character)
            parts.append("")
        else:
            return None
    if word_index != len(word) or any(not part for part in parts):
        return None
    return parts, boundaries


def _normalize_syllable_separators(
    generated: dict[str, Any], payload: dict[str, Any]
) -> None:
    config = SEMANTIC_NORMALIZERS.get("syllable_validation")
    if not isinstance(config, dict):
        return
    input_words_field = str(config.get("input_words_field") or "words")
    input_notation_field = str(config.get("input_notation_field") or "notation")
    output_items_field = str(config.get("output_items_field") or "items")
    word_field = str(config.get("word_field") or "word")
    syllabified_field = str(config.get("syllabified_field") or "syllabified")
    notation_separators = config.get("notation_separators", {})
    if not isinstance(notation_separators, dict):
        return
    desired = notation_separators.get(payload.get(input_notation_field))
    if not isinstance(desired, str) or len(desired) != 1:
        return
    separator_chars = {
        str(item)
        for item in config.get("accepted_separator_chars", notation_separators.values())
        if isinstance(item, str) and len(item) == 1
    }
    expected_words = [str(item) for item in payload.get(input_words_field, [])]
    items = generated.get(output_items_field, [])
    if not isinstance(items, list) or len(items) != len(expected_words):
        return
    for expected_word, item in zip(expected_words, items):
        if not isinstance(item, dict) or item.get(word_field) != expected_word:
            continue
        parsed = _syllable_parts_for_spelling(
            str(item.get(syllabified_field) or ""), expected_word, separator_chars
        )
        if parsed is None:
            continue
        parts, _boundaries = parsed
        item[syllabified_field] = desired.join(parts)


_EVIDENCE_STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "been", "by", "for", "from",
    "has", "have", "in", "is", "it", "of", "on", "or", "that", "the", "their",
    "this", "to", "was", "were", "will", "with",
}


def _evidence_text(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        return " ".join(_evidence_text(item) for item in value.values())
    if isinstance(value, list):
        return " ".join(_evidence_text(item) for item in value)
    return str(value) if value is not None else ""


def _evidence_number_tokens(value: Any) -> set[str]:
    return {
        token.replace(",", "")
        for token in re.findall(
            r"(?<![A-Za-z])[-+]?\d+(?:[.,]\d+)*", _evidence_text(value)
        )
    }


def _evidence_numeric_values(value: Any) -> set[float]:
    values: set[float] = set()
    for token in _evidence_number_tokens(value):
        try:
            parsed = float(token)
        except ValueError:
            continue
        if parsed == parsed and parsed not in (float("inf"), float("-inf")):
            values.add(round(parsed, 8))
    return values


def _evidence_content_tokens(value: Any) -> set[str]:
    tokens: set[str] = set()
    for token in re.findall(r"[a-z0-9]+", _evidence_text(value).lower()):
        if len(token) < 3 or token in _EVIDENCE_STOPWORDS:
            continue
        tokens.add(token[:-1] if token.endswith("s") and len(token) > 3 else token)
    return tokens


def _references_any_source(point: Any, sources: list[str]) -> bool:
    point_tokens = _evidence_content_tokens(point)
    if not point_tokens:
        return False
    point_numbers = _evidence_number_tokens(point)
    for source in sources:
        source_tokens = _evidence_content_tokens(source)
        overlap = point_tokens & source_tokens
        required_overlap = 1 if len(point_tokens) <= 3 else 2
        if len(overlap) < required_overlap:
            continue
        if point_numbers and not point_numbers <= _evidence_number_tokens(source):
            continue
        return True
    return False


def _numbers_equal(left: Any, right: Any, tolerance: float = 0.011) -> bool:
    return (
        isinstance(left, (int, float))
        and not isinstance(left, bool)
        and isinstance(right, (int, float))
        and not isinstance(right, bool)
        and abs(float(left) - float(right)) <= tolerance
    )


def _reconciliation_text(value: Any) -> str:
    return re.sub(r"[^a-z0-9]+", " ", str(value or "").casefold()).strip()


def _claim_survives_revision(claim: str, revised_copy: str) -> bool:
    normalized_claim = _reconciliation_text(claim)
    normalized_revision = _reconciliation_text(revised_copy)
    return bool(normalized_claim) and normalized_claim in normalized_revision


def _reconcile_contract_shape(generated: dict[str, Any]) -> dict[str, Any]:
    if SEMANTIC_EVIDENCE_SPEC.get("kind") != "copy_revision":
        return generated
    claims_field = str(SEMANTIC_EVIDENCE_SPEC["unsupported_claims_field"])
    claims = generated.get(claims_field)
    if isinstance(claims, dict):
        claims = [claims]
    if isinstance(claims, list):
        reconciled_claims: list[str] = []
        for item in claims:
            if isinstance(item, str):
                reconciled_claims.append(item)
                continue
            if not isinstance(item, dict):
                reconciled_claims.append(str(item))
                continue
            claim = next(
                (
                    item.get(name)
                    for name in ("claim", "text", "statement", "unsupported_claim")
                    if isinstance(item.get(name), str) and item.get(name).strip()
                ),
                None,
            )
            reconciled_claims.append(
                str(claim)
                if claim is not None
                else json.dumps(item, ensure_ascii=False, sort_keys=True)
            )
        generated[claims_field] = reconciled_claims
    edits_field = str(SEMANTIC_EVIDENCE_SPEC["edits_field"])
    edits = generated.get(edits_field)
    if isinstance(edits, dict):
        before_field = str(SEMANTIC_EVIDENCE_SPEC["before_field"])
        after_field = str(SEMANTIC_EVIDENCE_SPEC["after_field"])
        if before_field in edits or after_field in edits:
            generated[edits_field] = [edits]
        elif edits and all(isinstance(item, dict) for item in edits.values()):
            generated[edits_field] = list(edits.values())
    return generated


def _normalize_contract_evidence(generated: dict[str, Any]) -> None:
    if SEMANTIC_EVIDENCE_SPEC.get("kind") != "copy_revision":
        return
    revised_field = str(SEMANTIC_EVIDENCE_SPEC["revised_field"])
    claims_field = str(SEMANTIC_EVIDENCE_SPEC["unsupported_claims_field"])
    revised = str(generated.get(revised_field) or "")
    claims = generated.get(claims_field, [])
    if isinstance(claims, list):
        # Providers sometimes report claims they considered and then removed.
        # Drop edit suggestions that contain them, then retain only claims that
        # actually survived into the final copy before requiring an empty list.
        unsupported = [
            claim
            for claim in claims
            if isinstance(claim, str) and claim.strip()
        ]
        edits_field = str(SEMANTIC_EVIDENCE_SPEC["edits_field"])
        after_field = str(SEMANTIC_EVIDENCE_SPEC["after_field"])
        edits = generated.get(edits_field, [])
        if isinstance(edits, list):
            generated[edits_field] = [
                item
                for item in edits
                if isinstance(item, dict)
                and not any(
                    _claim_survives_revision(
                        claim, str(item.get(after_field) or "")
                    )
                    for claim in unsupported
                )
            ]
        generated[claims_field] = [
            claim for claim in unsupported if _claim_survives_revision(claim, revised)
        ]


def _parse_invoice_source(source: str) -> dict[str, Any] | None:
    number = r"[-+]?\d[\d,]*(?:\.\d+)?"
    line_pattern = re.compile(
        r"^\s*(.+?):\s*quantity\s+(" + number + r")\s+at\s+"
        r"(?:[A-Z]{3}\s+)?(" + number + r")(?:\s+each)?,\s*amount\s+"
        r"(?:[A-Z]{3}\s+)?(" + number + r")\s*$",
        flags=re.I,
    )
    total_pattern = re.compile(
        r"^\s*(subtotal|tax|shipping|discount|total)\s*:\s*"
        r"(?:[A-Z]{3}\s+)?(" + number + r")\s*$",
        flags=re.I,
    )

    def parsed_number(raw: str) -> float:
        return float(raw.replace(",", ""))

    lines: list[dict[str, Any]] = []
    totals: dict[str, float] = {}
    for raw_line in source.splitlines():
        line_match = line_pattern.match(raw_line)
        if line_match:
            description, quantity, unit_price, amount = line_match.groups()
            lines.append(
                {
                    "description": re.sub(r"\s+", " ", description).strip(),
                    "quantity": parsed_number(quantity),
                    "unit_price": parsed_number(unit_price),
                    "amount": parsed_number(amount),
                }
            )
            continue
        total_match = total_pattern.match(raw_line)
        if total_match:
            label, value = total_match.groups()
            totals[label.lower()] = parsed_number(value)
    required_totals = {"subtotal", "tax", "shipping", "discount", "total"}
    if not lines or not required_totals <= set(totals):
        return None
    return {"line_items": lines, **totals}


def _copy_revision_semantic_diff(
    generated: dict[str, Any], payload: dict[str, Any]
) -> list[str]:
    spec = SEMANTIC_EVIDENCE_SPEC
    details: list[str] = []
    source = str(payload.get(spec["source_field"]) or "").strip()
    revised = str(generated.get(spec["revised_field"]) or "").strip()
    if not revised or revised == source:
        details.append("$.revised_copy:semantic_revision_required")
    if generated.get(spec["unsupported_claims_field"], []):
        details.append("$.unsupported_claims:semantic_unsupported_claim")
    edits = generated.get(spec["edits_field"], [])
    if not isinstance(edits, list) or not edits:
        details.append("$.edits:semantic_edit_evidence_required")
    else:
        for item in edits:
            if (
                not isinstance(item, dict)
                or not str(item.get(spec["before_field"]) or "").strip()
                or not str(item.get(spec["after_field"]) or "").strip()
            ):
                details.append("$.edits[*]:semantic_before_after_pair_required")
                break
            if not str(item.get(spec["rationale_field"]) or "").strip():
                details.append("$.edits[*].rationale:semantic_edit_evidence_required")
                break
    if _evidence_number_tokens(revised) - _evidence_number_tokens(payload):
        details.append("$.revised_copy:semantic_invented_number")
    return details


def _indexed_facts_semantic_diff(
    generated: dict[str, Any], payload: dict[str, Any]
) -> list[str]:
    spec = SEMANTIC_EVIDENCE_SPEC
    details: list[str] = []
    facts = payload.get(spec["facts_field"], [])
    indexes = generated.get(spec["indexes_field"], [])
    valid = (
        isinstance(facts, list)
        and isinstance(indexes, list)
        and bool(indexes)
        and len(indexes) == len(set(indexes))
        and all(
            isinstance(index, int)
            and not isinstance(index, bool)
            and 0 <= index < len(facts)
            for index in indexes
        )
    )
    if not valid:
        details.append("$.fact_indexes_used:semantic_fact_index")
        return details
    selected = [str(facts[index]) for index in indexes]
    points = generated.get(spec["points_field"], [])
    if not isinstance(points, list) or not points or any(
        not _references_any_source(point, selected) for point in points
    ):
        details.append("$.key_points:semantic_fact_reference")
    return details


def _quoted_review_semantic_diff(
    generated: dict[str, Any], payload: dict[str, Any]
) -> list[str]:
    spec = SEMANTIC_EVIDENCE_SPEC
    details: list[str] = []
    source = str(payload.get(spec["source_field"]) or "")
    for item_field in spec["quoted_item_fields"]:
        items = generated.get(item_field, [])
        if not isinstance(items, list) or any(
            not isinstance(item, dict)
            or not str(item.get(spec["quote_field"]) or "").strip()
            or str(item.get(spec["quote_field"])) not in source
            for item in items
        ):
            details.append(f"$.{item_field}[*].source_quote:semantic_source_quote")
    if not str(generated.get(spec["disclaimer_field"]) or "").strip():
        details.append("$.disclaimer:semantic_disclaimer_required")
    return details


def _source_referenced_notes_semantic_diff(
    generated: dict[str, Any], payload: dict[str, Any]
) -> list[str]:
    spec = SEMANTIC_EVIDENCE_SPEC
    details: list[str] = []
    source = str(payload.get(spec["source_field"]) or "")
    references = generated.get(spec["references_field"], [])
    if not isinstance(references, list) or not references or any(
        not isinstance(item, dict)
        or not str(item.get(spec["quote_field"]) or "").strip()
        or str(item.get(spec["quote_field"])) not in source
        for item in references
    ):
        details.append("$.action_items[*].source_quote:semantic_source_quote")
    points: list[Any] = []
    for field in spec["point_fields"]:
        value = generated.get(field)
        points.extend(value if isinstance(value, list) else [value])
    points = [point for point in points if str(point or "").strip()]
    if not points or any(not _references_any_source(point, [source]) for point in points):
        details.append("$.summary:semantic_fact_reference")
    return details


def _invoice_semantic_diff(
    generated: dict[str, Any], payload: dict[str, Any]
) -> list[str]:
    spec = SEMANTIC_EVIDENCE_SPEC
    parsed = _parse_invoice_source(str(payload.get(spec["source_field"]) or ""))
    if parsed is None:
        return ["$:semantic_invoice_source_unparseable"]
    details: list[str] = []

    def identity(value: Any) -> str:
        return re.sub(r"\s+", " ", str(value or "")).strip().casefold()

    expected = {identity(item["description"]): item for item in parsed["line_items"]}
    actual_items = generated.get(spec["line_items_field"], [])
    actual = {
        identity(item.get("description")): item
        for item in actual_items
        if isinstance(item, dict)
    } if isinstance(actual_items, list) else {}
    if set(actual) != set(expected) or len(actual) != len(actual_items):
        details.append("$.line_items:semantic_invoice_identity")
    for name, expected_item in expected.items():
        item = actual.get(name, {})
        if any(
            not _numbers_equal(item.get(field), expected_item[field])
            for field in ("quantity", "unit_price", "amount")
        ):
            details.append("$.line_items:semantic_invoice_values")
            break
    for field in spec["total_fields"]:
        if not _numbers_equal(generated.get(field), parsed[field]):
            details.append(f"$.{field}:semantic_invoice_total")
    expected_arithmetic = "pass" if (
        all(
            _numbers_equal(item["amount"], item["quantity"] * item["unit_price"])
            for item in parsed["line_items"]
        )
        and _numbers_equal(
            parsed["subtotal"], sum(item["amount"] for item in parsed["line_items"])
        )
        and _numbers_equal(
            parsed["total"],
            parsed["subtotal"] + parsed["tax"] + parsed["shipping"] - parsed["discount"],
        )
    ) else "fail"
    if generated.get(spec["arithmetic_check_field"]) != expected_arithmetic:
        details.append("$.arithmetic_check:semantic_invoice_arithmetic")
    return details


def _budget_semantic_diff(
    generated: dict[str, Any], payload: dict[str, Any]
) -> list[str]:
    spec = SEMANTIC_EVIDENCE_SPEC
    details: list[str] = []
    for field in (spec["period_field"], spec["currency_field"]):
        if generated.get(field) != payload.get(field):
            details.append(f"$.{field}:semantic_input_value")
    expected: dict[tuple[str, str], dict[str, float]] = {}
    departments: dict[str, dict[str, float]] = {}
    derived_numbers: list[float] = []
    for line in payload.get(spec["lines_field"], []):
        budget = float(sum(line.get("monthly_budget", [])))
        actual = float(sum(line.get("monthly_actual", [])))
        variance = actual - budget
        variance_percent = None if budget == 0 else round(100 * variance / budget, 2)
        expected[(str(line.get("department")), str(line.get("category")))] = {
            "budget_total": budget,
            "actual_total": actual,
            "variance_amount": variance,
            "variance_percent": variance_percent,
        }
        derived_numbers.extend([budget, actual, variance])
        if variance_percent is not None:
            derived_numbers.append(variance_percent)
        department = departments.setdefault(
            str(line.get("department")), {"budget_total": 0.0, "actual_total": 0.0}
        )
        department["budget_total"] += budget
        department["actual_total"] += actual
    returned = {
        (str(item.get("department")), str(item.get("category"))): item
        for item in generated.get("line_items", [])
        if isinstance(item, dict)
    }
    if set(returned) != set(expected):
        details.append("$.line_items:semantic_budget_identity")
    for key, expected_item in expected.items():
        item = returned.get(key, {})
        for field, value in expected_item.items():
            if value is None:
                valid = item.get(field) is None
            else:
                valid = _numbers_equal(item.get(field), value)
            if not valid:
                details.append("$.line_items:semantic_budget_arithmetic")
                break
    returned_departments = {
        str(item.get("department")): item
        for item in generated.get("department_totals", [])
        if isinstance(item, dict)
    }
    if set(returned_departments) != set(departments):
        details.append("$.department_totals:semantic_budget_identity")
    for name, expected_item in departments.items():
        item = returned_departments.get(name, {})
        department_variance = (
            expected_item["actual_total"] - expected_item["budget_total"]
        )
        department_percent = (
            None
            if expected_item["budget_total"] == 0
            else round(
                100 * department_variance / expected_item["budget_total"], 2
            )
        )
        derived_numbers.extend(
            [
                expected_item["budget_total"],
                expected_item["actual_total"],
                department_variance,
            ]
        )
        if department_percent is not None:
            derived_numbers.append(department_percent)
        if not (
            _numbers_equal(item.get("budget_total"), expected_item["budget_total"])
            and _numbers_equal(item.get("actual_total"), expected_item["actual_total"])
            and _numbers_equal(
                item.get("variance_amount"),
                department_variance,
            )
        ):
            details.append("$.department_totals:semantic_budget_arithmetic")
            break
    company_budget = sum(item["budget_total"] for item in expected.values())
    company_actual = sum(item["actual_total"] for item in expected.values())
    forecast_total = company_actual
    target_total = float(payload.get(spec["target_field"], 0))
    target_variance = company_budget - target_total
    for field, value in (
        ("company_budget_total", company_budget),
        ("company_actual_total", company_actual),
        ("forecast_total", forecast_total),
        ("target_variance", target_variance),
    ):
        if not _numbers_equal(generated.get(field), value):
            details.append(f"$.{field}:semantic_budget_arithmetic")
    company_variance = company_actual - company_budget
    forecast_target_variance = forecast_total - target_total
    derived_numbers.extend(
        [
            company_budget,
            company_actual,
            forecast_total,
            target_variance,
            company_variance,
            forecast_target_variance,
        ]
    )
    if company_budget != 0:
        derived_numbers.append(round(100 * company_variance / company_budget, 2))
    if target_total != 0:
        derived_numbers.append(
            round(100 * forecast_target_variance / target_total, 2)
        )
    allowed_numbers = _evidence_numeric_values(payload)
    allowed_numbers.update(round(value, 8) for value in derived_numbers)
    # Narrative variance descriptions may state an absolute over/under amount
    # while typed numeric fields preserve the signed contract value.
    allowed_numbers.update(round(abs(value), 8) for value in derived_numbers)
    unexpected_numbers = {
        value
        for value in _evidence_numeric_values(generated)
        if not any(abs(value - allowed) <= 0.011 for allowed in allowed_numbers)
    }
    if unexpected_numbers:
        details.append("$:semantic_invented_number")
    return details


def _contract_evidence_validation_diff(
    generated: dict[str, Any], payload: dict[str, Any]
) -> list[str]:
    kind = SEMANTIC_EVIDENCE_SPEC.get("kind")
    if kind == "copy_revision":
        return _copy_revision_semantic_diff(generated, payload)
    if kind == "indexed_facts":
        return _indexed_facts_semantic_diff(generated, payload)
    if kind == "quoted_risk_review":
        return _quoted_review_semantic_diff(generated, payload)
    if kind == "source_referenced_notes":
        return _source_referenced_notes_semantic_diff(generated, payload)
    if kind == "invoice_arithmetic":
        return _invoice_semantic_diff(generated, payload)
    if kind == "budget_arithmetic":
        return _budget_semantic_diff(generated, payload)
    if kind == "grounded_copy":
        details: list[str] = []
        output_text = _evidence_text(generated).casefold()
        for field in SEMANTIC_EVIDENCE_SPEC["required_input_fields"]:
            if str(payload.get(field) or "").strip().casefold() not in output_text:
                details.append(f"$:{field}_missing")
        if _evidence_number_tokens(generated) - _evidence_number_tokens(payload):
            details.append("$:semantic_invented_number")
        return details
    return []


def _semantic_normalize(
    generated: dict[str, Any], payload: dict[str, Any]
) -> dict[str, Any]:
    _normalize_contract_evidence(generated)
    if isinstance(SEMANTIC_NORMALIZERS.get("digraph_spans"), dict):
        generated["occurrences"] = _reviewed_digraph_occurrences(payload, generated)
        generated["summary"] = list(
            dict.fromkeys(item["text"].lower() for item in generated["occurrences"])
        )
    _normalize_target_word_containment(generated, payload)
    _normalize_phoneme_containment(generated, payload)
    _normalize_syllable_separators(generated, payload)
    for rule in SEMANTIC_NORMALIZERS.get("flag_fields", []):
        if isinstance(rule, dict) and payload.get(rule.get("flag")) is False:
            _strip_output_path(generated, rule.get("path", []))
    return generated


def _semantic_validation_diff(
    generated: dict[str, Any], payload: dict[str, Any]
) -> str:
    details: list[str] = []
    if isinstance(SEMANTIC_NORMALIZERS.get("digraph_spans"), dict):
        expected = _reviewed_digraph_occurrences(payload, {})
        fields = ("text", "word", "start", "end", "type")
        expected_signatures = [tuple(item.get(field) for field in fields) for item in expected]
        actual_signatures = [
            tuple(item.get(field) for field in fields)
            for item in generated.get("occurrences", [])
            if isinstance(item, dict)
        ]
        if actual_signatures != expected_signatures:
            details.append(
                "$.occurrences:semantic_source_spans(expected="
                + str(len(expected_signatures))
                + ",actual="
                + str(len(actual_signatures))
                + ")"
            )
        expected_summary = list(dict.fromkeys(item["text"].lower() for item in expected))
        if generated.get("summary") != expected_summary:
            details.append("$.summary:semantic_digraph_coverage")

    config = SEMANTIC_NORMALIZERS.get("phoneme_containment")
    if isinstance(config, dict):
        requested = [str(item) for item in payload.get("phonemes", [])]
        phoneme_map = config.get("phoneme_to_graphemes", {})
        words = generated.get("words", [])
        if len(words) != payload.get("word_count"):
            details.append(
                "$.words:semantic_word_count(expected="
                + str(payload.get("word_count"))
                + ",actual="
                + str(len(words))
                + ")"
            )
        covered: set[str] = set()
        for item in words:
            matched, _spans = _matching_requested_phonemes(
                str(item.get("word") or ""), requested, phoneme_map
            )
            if item.get("matched_phonemes") != matched or not matched:
                details.append("$.words:semantic_phoneme_containment")
                break
            covered.update(matched)
        if any(phoneme not in covered for phoneme in requested):
            details.append("$.coverage:semantic_requested_phonemes")

    config = SEMANTIC_NORMALIZERS.get("target_word_containment")
    if isinstance(config, dict):
        request_field = str(config.get("request_field") or "phonics_patterns")
        items_field = str(config.get("items_field") or "sentences")
        target_field = str(config.get("target_field") or "target_words")
        requested = [str(item) for item in payload.get(request_field, [])]
        covered: set[str] = set()
        for index, item in enumerate(generated.get(items_field, [])):
            targets = item.get(target_field, []) if isinstance(item, dict) else []
            if not targets or any(
                not _target_in_sentence(str(item.get("text") or ""), str(word))
                or not any(_matches_reviewed_pattern(str(word), pattern, config) for pattern in requested)
                for word in targets
            ):
                details.append(
                    f"$.{items_field}[{index}].{target_field}:semantic_target_containment"
                )
            for word in targets:
                covered.update(
                    pattern
                    for pattern in requested
                    if _matches_reviewed_pattern(str(word), pattern, config)
                )
        if len(generated.get(items_field, [])) != payload.get("num_sentences"):
            details.append(
                "$.sentences:semantic_sentence_count(expected="
                + str(payload.get("num_sentences"))
                + ",actual="
                + str(len(generated.get(items_field, [])))
                + ")"
            )
        expected_coverage = [pattern for pattern in requested if pattern in covered]
        if generated.get("coverage") != expected_coverage or len(covered) != len(requested):
            details.append("$.coverage:semantic_requested_patterns")

    config = SEMANTIC_NORMALIZERS.get("syllable_validation")
    if isinstance(config, dict):
        input_words_field = str(config.get("input_words_field") or "words")
        input_notation_field = str(config.get("input_notation_field") or "notation")
        output_items_field = str(config.get("output_items_field") or "items")
        word_field = str(config.get("word_field") or "word")
        syllabified_field = str(config.get("syllabified_field") or "syllabified")
        count_field = str(config.get("count_field") or "syllable_count")
        notation_separators = config.get("notation_separators", {})
        desired = (
            notation_separators.get(payload.get(input_notation_field))
            if isinstance(notation_separators, dict)
            else None
        )
        separator_chars = {
            str(item)
            for item in config.get("accepted_separator_chars", [])
            if isinstance(item, str) and len(item) == 1
        }
        expected_words = [str(item) for item in payload.get(input_words_field, [])]
        items = generated.get(output_items_field, [])
        actual_words = [
            str(item.get(word_field) or "") if isinstance(item, dict) else ""
            for item in items
        ] if isinstance(items, list) else []
        if actual_words != expected_words:
            details.append(
                f"$.{output_items_field}:semantic_word_order(expected_count={len(expected_words)},actual_count={len(actual_words)})"
            )
        for index, (expected_word, item) in enumerate(zip(expected_words, items)):
            if not isinstance(item, dict) or item.get(word_field) != expected_word:
                continue
            parsed = _syllable_parts_for_spelling(
                str(item.get(syllabified_field) or ""), expected_word, separator_chars
            )
            path = f"$.{output_items_field}[{index}].{syllabified_field}"
            if parsed is None:
                details.append(path + ":semantic_spelling_preservation")
                continue
            parts, boundaries = parsed
            count = item.get(count_field)
            if not isinstance(count, int) or len(parts) != count:
                details.append(path + ":semantic_syllable_count")
            if len(parts) > 1 and (
                not isinstance(desired, str)
                or any(boundary != desired for boundary in boundaries)
            ):
                details.append(path + ":semantic_separator")

    for rule in SEMANTIC_NORMALIZERS.get("flag_fields", []):
        if not isinstance(rule, dict) or payload.get(rule.get("flag")) is not False:
            continue
        path = rule.get("path", [])
        if _output_path_exists(generated, path):
            details.append("$" + "".join("[*]" if part == "*" else "." + part for part in path) + ":flag_disabled")
    details.extend(_contract_evidence_validation_diff(generated, payload))
    return ";".join(dict.fromkeys(details))


def _validation_diff(instance: Any, schema: dict[str, Any]) -> str:
    errors = sorted(
        Draft202012Validator(schema).iter_errors(instance),
        key=lambda error: (list(error.absolute_path), str(error.validator)),
    )
    details: list[str] = []
    for error in errors[:20]:
        path = "$" + "".join(
            f"[{part}]" if isinstance(part, int) else f".{part}" for part in error.absolute_path
        )
        if error.validator == "required" and isinstance(error.instance, dict):
            missing = [name for name in error.validator_value if name not in error.instance]
            detail = "required(" + ",".join(missing) + ")"
        elif error.validator == "additionalProperties" and isinstance(error.instance, dict):
            allowed = set(error.schema.get("properties", {}))
            extra_count = sum(1 for name in error.instance if name not in allowed)
            detail = f"additionalProperties(count={extra_count})"
        elif error.validator == "type":
            detail = "type(expected=" + str(error.validator_value) + ")"
        elif error.validator in {"minLength", "maxLength", "minItems", "maxItems", "minimum", "maximum", "enum", "const", "uniqueItems"}:
            detail = str(error.validator) + "(expected=" + str(error.validator_value)[:160] + ")"
        else:
            detail = str(error.validator)
        details.append(path + ":" + detail)
    if len(errors) > 20:
        details.append(f"...+{len(errors) - 20}_more")
    return ";".join(details)


def _provider_request(
    base_url: str,
    model: str,
    messages: list[dict[str, str]],
) -> tuple[str, dict[str, Any]]:
    request_body = {
        "model": model,
        "messages": messages,
        "temperature": LIVE_TEMPERATURE,
        "max_tokens": LIVE_MAX_TOKENS,
        "response_format": {"type": "json_object"},
        "thinking": {"type": "disabled"},
    }
    request = urllib.request.Request(
        base_url + "/chat/completions",
        data=json.dumps(request_body).encode("utf-8"),
        headers={
            "Authorization": "Bearer " + os.environ[LIVE_API_KEY_ENV],
            "Content-Type": "application/json",
            "User-Agent": "Omo-Skill-Runner/0.2",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=LIVE_TIMEOUT_SECONDS) as response:
            raw = response.read(2_000_001)
    except urllib.error.HTTPError as exc:
        raise ProviderCallError(f"LLM_HTTP_{exc.code}") from exc
    except (urllib.error.URLError, TimeoutError) as exc:
        raise ProviderCallError("LLM_UNAVAILABLE") from exc
    if len(raw) > 2_000_000:
        raise ProviderCallError("LLM_RESPONSE_TOO_LARGE")
    try:
        provider_response = json.loads(raw)
        content = str(provider_response["choices"][0]["message"]["content"])
    except Exception as exc:
        raise ProviderCallError("LLM_RESPONSE_INVALID") from exc
    return content, provider_response


def _candidate_for_schema(
    content: str,
    payload: dict[str, Any],
    schema: dict[str, Any],
    *,
    apply_semantic_rules: bool,
) -> tuple[dict[str, Any] | None, str]:
    try:
        parsed = _extract_json_object(content)
    except Exception:
        return None, "$:invalid_json"
    repaired = _repair_to_schema(_reconcile_contract_shape(parsed), schema, payload)
    normalized = _semantic_normalize(repaired, payload) if apply_semantic_rules else repaired
    diffs = [_validation_diff(normalized, schema)]
    if apply_semantic_rules:
        diffs.append(_semantic_validation_diff(normalized, payload))
    return normalized, ";".join(diff for diff in diffs if diff)


def _candidate(
    content: str, payload: dict[str, Any]
) -> tuple[dict[str, Any] | None, str]:
    return _candidate_for_schema(
        content, payload, LIVE_MODEL_OUTPUT_SCHEMA, apply_semantic_rules=True
    )


def _structured_completion(
    payload: dict[str, Any],
    schema: dict[str, Any],
    system_prompt: str,
    *,
    apply_semantic_rules: bool,
    user_label: str,
    workflow_instructions: str | None = None,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    payload_bytes = json.dumps(
        payload,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")
    if len(payload_bytes) > LIVE_MAX_INPUT_BYTES:
        raise ValueError("INPUT_LIMIT_EXCEEDED")
    missing = [name for name in readiness()["required_env_names"] if not os.environ.get(name)]
    if missing:
        raise WorkflowNotReady("MISSING_REQUIRED_ENV:" + ",".join(sorted(missing)))
    base_url = os.environ[LIVE_BASE_URL_ENV].rstrip("/")
    if not base_url.startswith("https://"):
        raise WorkflowNotReady("LLM_BASE_URL_MUST_BE_HTTPS")
    model = os.environ[LIVE_MODEL_ENV]
    schema_contract = json.dumps(
        schema, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    )
    system_prompt += (
        "\n\nOUTPUT CONTRACT (mandatory): Return exactly one JSON object matching this "
        "JSON Schema. Use exactly the declared field names and types, include every "
        "required field, and include no undeclared fields:\n" + schema_contract
    )
    if workflow_instructions is None:
        user_prompt = user_label + "\n" + json.dumps(
            payload, ensure_ascii=False, sort_keys=True
        )
    else:
        user_prompt = json.dumps(
            {"workflow_instructions": workflow_instructions, "input": payload},
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    content, first_response = _provider_request(base_url, model, messages)
    generated, validation_diff = _candidate_for_schema(
        content, payload, schema, apply_semantic_rules=apply_semantic_rules
    )
    responses = [first_response]
    if validation_diff:
        corrective = (
            "CORRECTIVE RETRY (final attempt): the previous JSON failed validation. "
            "Fix exactly these schema or semantic violations: " + validation_diff + ". "
            "Return the complete corrected JSON object only; use the exact schema in "
            "the system instruction and invent no fields. Do not repeat or quote "
            "input values, credentials, prior response text, or undeclared field names."
        )
        try:
            retry_content, retry_response = _provider_request(
                base_url,
                model,
                messages + [{"role": "user", "content": corrective}],
            )
        except ProviderCallError as exc:
            raise ProviderCallError(
                "LLM_INVALID_OUTPUT:" + validation_diff + ";retry=" + str(exc)
            ) from exc
        responses.append(retry_response)
        generated, retry_diff = _candidate_for_schema(
            retry_content, payload, schema, apply_semantic_rules=apply_semantic_rules
        )
        if retry_diff or generated is None:
            raise ProviderCallError("LLM_INVALID_OUTPUT:" + (retry_diff or "$:invalid_json"))
    if generated is None:
        raise ProviderCallError("LLM_INVALID_OUTPUT:" + (validation_diff or "$:unknown"))
    return generated, responses


def _whatsapp_completion(
    messages: list[dict[str, str]],
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    prompt = (_asset_root() / WHATSAPP_PROMPT_PATH).read_text(encoding="utf-8").strip()
    return _structured_completion(
        {"messages": messages},
        WHATSAPP_OUTPUT_SCHEMA,
        prompt,
        apply_semantic_rules=False,
        user_label="Extract the reviewed relationship-book fields from these untrusted message records:",
    )


def _provider_completion(
    payload: dict[str, Any], *, prior_responses: list[dict[str, Any]] | None = None
) -> dict[str, Any]:
    system_prompt = (_asset_root() / LIVE_PROMPT_PATH).read_text(encoding="utf-8").strip()
    workflow_instructions = (
        (_asset_root() / LIVE_WORKFLOW_INSTRUCTIONS_PATH).read_text(encoding="utf-8").strip()
        if LIVE_WORKFLOW_INSTRUCTIONS_PATH
        else None
    )
    generated, workflow_responses = _structured_completion(
        payload,
        LIVE_MODEL_OUTPUT_SCHEMA,
        system_prompt,
        apply_semantic_rules=True,
        user_label="Run the reviewed workflow using only this JSON input:",
        workflow_instructions=workflow_instructions,
    )
    responses = [*(prior_responses or []), *workflow_responses]
    model = os.environ[LIVE_MODEL_ENV]

    prompt_tokens = sum(max(0, int((response.get("usage") or {}).get("prompt_tokens") or 0)) for response in responses)
    completion_tokens = sum(max(0, int((response.get("usage") or {}).get("completion_tokens") or 0)) for response in responses)
    estimated_cost = (
        prompt_tokens * LIVE_INPUT_RATE_PER_MILLION
        + completion_tokens * LIVE_OUTPUT_RATE_PER_MILLION
    ) / 1_000_000
    return {
        "run_id": "run-" + str(uuid.uuid4()),
        "status": "completed",
        "workflow_version": WORKFLOW_VERSION,
        **generated,
        "usage": {
            "provider": LIVE_PROVIDER,
            "model": str(responses[-1].get("model") or model),
            "llm_calls": len(responses),
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "estimated_cost_usd": round(estimated_cost, 8),
        },
    }









Executor = Callable[[dict[str, Any]], dict[str, Any]]
InputExtractor = Callable[[list[dict[str, str]]], Any]
FindingsWriter = Callable[[dict[str, Any]], Any]


def execute_workflow(
    payload: dict[str, Any],
    *,
    executor: Executor | None = None,
    input_extractor: InputExtractor | None = None,
    findings_writer: FindingsWriter | None = None,
    artifact_root: Path | None = None,
    artifact_signing_key: str | None = None,
    clock: Callable[[], float] | None = None,
) -> dict[str, Any]:
    """Validate, execute once, and validate output.

    A mock executor is an explicit offline test seam. The generated live
    candidate never substitutes mock artifacts for unavailable providers.
    """
    validate_instance(payload, "input.json")
    normalized_payload, adapter_responses = payload, []
    if executor is None:
        if findings_writer is None:
            state = readiness()
            if not state["can_submit"]:
                raise WorkflowNotReady(
                    "; ".join(reason["code"] for reason in state["blockers"])
                )
        if findings_writer is not None:
            raise TypeError("findings_writer is only valid for analysis orchestrators")
        result = _provider_completion(normalized_payload, prior_responses=adapter_responses)
    else:
        result = executor(normalized_payload)

    validate_instance(result, "output.json")
    return result


runtime_image = (
    modal.Image.debian_slim(python_version="3.12")
    .uv_pip_install(
        "modal==1.5.0",
        "fastapi==0.109.0",
        "jsonschema==4.26.0",
    )
    .add_local_dir(LOCAL_ROOT / "schemas", IMAGE_ROOT / "schemas", copy=True)
    .add_local_dir(LOCAL_ROOT / "prompts", IMAGE_ROOT / "prompts", copy=True)
    .add_local_file(LOCAL_ROOT / "manifest.json", str(IMAGE_ROOT / "manifest.json"), copy=True)
    .add_local_file(LOCAL_ROOT / "capability-manifest.json", str(IMAGE_ROOT / "capability-manifest.json"), copy=True)




)

app = modal.App(APP_NAME)


@app.function(
    image=runtime_image,
    cpu=1.0,
    memory=512,
    timeout=270,
    min_containers=0,
    max_containers=4,
    scaledown_window=5,
    secrets=[modal.Secret.from_name('omo-skill-providers-gemini')],
)
def run_workflow(payload: dict[str, Any]) -> dict[str, Any]:
    return execute_workflow(payload)


SpawnRunner = Callable[[dict[str, Any]], str]
LookupResult = Callable[[str], dict[str, Any]]


def create_fastapi_app(
    spawn_runner: SpawnRunner | None = None,
    lookup_result: LookupResult | None = None,
    *,
    ready_override: bool | None = None,
) -> Any:
    from fastapi import Body, FastAPI, HTTPException
    from fastapi.responses import JSONResponse, Response
    from jsonschema import ValidationError

    web = FastAPI(title='Gemini Ticket Priority Canary', version='1.0.0')

    def default_spawn(payload: dict[str, Any]) -> str:
        return run_workflow.spawn(payload).object_id

    def default_lookup(call_id: str) -> dict[str, Any]:
        return modal.FunctionCall.from_id(call_id).get(timeout=0)

    spawn = spawn_runner or default_spawn
    lookup = lookup_result or default_lookup

    @web.post("/v1/runs", status_code=202)
    async def submit(body: Any = Body(...)) -> Any:
        try:
            validate_instance(body, "input.json")
        except ValidationError as exc:
            raise HTTPException(status_code=422, detail=exc.message) from exc


        state = readiness()
        can_submit = state["can_submit"] if ready_override is None else ready_override
        if not can_submit:
            return JSONResponse(
                {
                    "status": "not_ready",
                    "error": {
                        "code": "WORKFLOW_NOT_READY",
                        "blockers": state["blockers"],
                    },
                },
                status_code=503,
            )

        call_id = spawn(body)
        run_id = str(uuid.uuid4())
        return {
            "run_id": run_id,
            "call_id": call_id,
            "status": "accepted",
            "result_url": f"/v1/runs/{call_id}",
        }

    @web.get("/v1/runs/{call_id}")
    async def get_result(call_id: str) -> Any:
        try:
            result = lookup(call_id)
            validate_instance(result, "output.json")
            return result
        except TimeoutError:
            return JSONResponse({"call_id": call_id, "status": "running"}, status_code=202)
        except Exception:
            return JSONResponse(
                {"call_id": call_id, "status": "failed", "error": {"code": "RUN_FAILED"}},
                status_code=500,
            )


    return web


@app.function(
    image=runtime_image,
    min_containers=0,
    max_containers=20,
    scaledown_window=2,
)
@modal.concurrent(max_inputs=20)
@modal.asgi_app(requires_proxy_auth=True)
def api() -> Any:
    return create_fastapi_app()
